import {PowerSource,Coil,Contact,Junction,Lamp,Motor} from '../model/components.js';
import {gridExtent,Schematic} from '../model/Schematic.js';

export class Editor{
 constructor(options){Object.assign(this,options);this.mode='EDIT';this.tool=null;this.styleId='RED';this.wireDescription='';this.selection=null;this.selections=new Set();this.selectedWirePoint=null;this.scale=1;this.pan={x:0,y:0};this.history=[];this.future=[];this.space=false;this.bind();this.resetView()}
 setSchematic(s){this.schematic=s;this.selection=null;this.selections.clear();this.history=[];this.future=[];this.resetView();this.render()}
 bind(){this.svg.addEventListener('pointerdown',e=>this.down(e));this.svg.addEventListener('pointermove',e=>this.move(e));this.svg.addEventListener('pointerup',e=>this.up(e));this.svg.addEventListener('contextmenu',e=>e.preventDefault());this.svg.addEventListener('wheel',e=>this.wheel(e),{passive:false});window.addEventListener('keydown',e=>this.key(e,true));window.addEventListener('keyup',e=>this.key(e,false))}
 point(e){const r=this.svg.getBoundingClientRect();return{x:(e.clientX-r.left-this.pan.x)/this.scale,y:(e.clientY-r.top-this.pan.y)/this.scale}}
 snap(p){const g=this.schematic.grid.snapGrid;if(!g.enabled)return p;return{x:Math.round(p.x/g.stepX)*g.stepX,y:Math.round(p.y/g.stepY)*g.stepY}}
 down(e){this.svg.focus();if(e.button===2){e.preventDefault();this.drag={kind:'pan',button:'right',start:{x:e.clientX,y:e.clientY},origin:{...this.pan},moved:false};this.svg.setPointerCapture(e.pointerId);this.onStatus(null,'Déplacement du plan');return}const exact=this.point(e);if(e.button===0&&this.pointPicker){const picker=this.pointPicker;this.pointPicker=null;picker(exact);return}const p=this.snap(exact),terminal=e.target.dataset.terminal,id=e.target.closest('[data-id]')?.dataset.id,wirePoint=e.target.dataset.wirePoint;if(e.button===1||this.space){this.drag={kind:'pan',button:'middle',start:{x:e.clientX,y:e.clientY},origin:{...this.pan},moved:false};this.svg.setPointerCapture(e.pointerId);return}if(this.mode==='SIMULATION'){const c=this.schematic.getComponent(id);if(c?.type==='contact'&&c.controlType==='manual'){c.manualActivated=!c.manualActivated;this.onChange('simulation')}return}if(wirePoint!==undefined){const wireId=e.target.dataset.wireId,index=Number(wirePoint),wire=this.schematic.getWire(wireId);this.select(wireId);this.selectedWirePoint=index;this.snapshot();this.drag={kind:'wirePoint',wireId,index,originalPoints:wire.points.map(point=>({...point})),previousOrientation:this.segmentOrientation(wire.points[index-1],wire.points[index]),nextOrientation:this.segmentOrientation(wire.points[index],wire.points[index+1])};this.svg.setPointerCapture(e.pointerId);this.render();this.onStatus(p,'Sommet sélectionné — glissez ou appuyez sur Suppr');return}if(this.tool==='wire'){this.wireClick(terminal,p,e.shiftKey);return}if(this.tool&&!id){this.snapshot();this.add(this.tool,p);return}if(id){this.select(id);const c=this.schematic.getComponent(id);if(c){this.snapshot();this.drag={kind:'component',id,offset:{x:p.x-c.position.x,y:p.y-c.position.y}};this.svg.setPointerCapture(e.pointerId)}}else{this.drag={kind:'marquee',start:p,current:p};this.marquee=this.normalizeRect(p,p);this.svg.setPointerCapture(e.pointerId);this.render()}}
 move(e){const p=this.point(e);this.onStatus(this.snap(p));if(this.drag?.kind==='pan'){const dx=e.clientX-this.drag.start.x,dy=e.clientY-this.drag.start.y;this.drag.moved=this.drag.moved||Math.hypot(dx,dy)>3;this.pan={x:this.drag.origin.x+dx,y:this.drag.origin.y+dy};this.applyTransform()}if(this.drag?.kind==='component'){const c=this.schematic.getComponent(this.drag.id),q=this.snap({x:p.x-this.drag.offset.x,y:p.y-this.drag.offset.y});c.position=q;this.syncConnectedWires(c);this.render()}if(this.drag?.kind==='wirePoint'){this.moveWirePoint(this.drag,this.snap(p));this.render()}if(this.drag?.kind==='marquee'){this.drag.current=p;this.marquee=this.normalizeRect(this.drag.start,p);this.render();this.onStatus(p,'Relâchez pour sélectionner les éléments entièrement contenus')}if(this.pendingWire){const q=this.constrain(this.pendingWire.points.at(-1),this.snap(p),e.shiftKey);this.preview=[...this.pendingWire.points,q];this.render()}}
 up(){if(this.drag?.kind==='pan'&&this.drag.button==='right'&&!this.drag.moved){this.drag=null;this.cancelAction();return}if(this.drag?.kind==='component')this.onChange('move');if(this.drag?.kind==='wirePoint')this.onChange('wire-point');if(this.drag?.kind==='marquee'){const rect=this.normalizeRect(this.drag.start,this.drag.current);this.selectMany(rect.width<3&&rect.height<3?[]:this.itemsInRect(rect));this.marquee=null}this.drag=null;this.render()}
 add(tool,p){let c;if(tool==='powerSource')c=new PowerSource({id:this.schematic.nextId('PS'),label:'Alimentation 24 VAC',position:p});if(tool==='coil')c=new Coil({id:this.schematic.nextId('R'),label:'RELAIS',relayType:'',position:p});if(tool==='lamp')c=new Lamp({id:this.schematic.nextId('L'),label:'LAMPE',number:'',position:p});if(tool==='motor')c=new Motor({id:this.schematic.nextId('M'),label:'MOTEUR',position:p});if(['contactNO','contactNC','contactChangeover'].includes(tool))c=new Contact({id:this.schematic.nextId('SW'),label:'CONTACT',position:p,contactType:tool==='contactNO'?'NO':tool==='contactNC'?'NC':'CHANGEOVER'});if(tool==='junction')c=new Junction({id:this.schematic.nextId('J'),label:'',position:p});if(c){this.schematic.components.push(c);this.select(c.id);this.onChange('add')}}
 wireClick(terminal,p,free){if(!this.pendingWire){if(!terminal){this.onStatus(p,'Commencez le fil sur une borne');return}this.pendingWire={terminal,points:[p]};this.preview=[p,p];this.onStatus(p,'Cliquez pour ajouter des points, puis sur une borne pour terminer');return}const last=this.pendingWire.points.at(-1);if(terminal&&terminal!==this.pendingWire.terminal){const q=this.constrain(last,p,free),points=[...this.pendingWire.points];if(q.x!==last.x||q.y!==last.y)points.push(q);if(q.x!==p.x||q.y!==p.y)points.push(p);this.snapshot();const w={id:this.schematic.nextId('W'),styleId:this.styleId,description:this.wireDescription.trim(),from:this.pendingWire.terminal,to:terminal,points};this.schematic.addWire(w);this.pendingWire=null;this.preview=null;this.select(w.id);this.onChange('wire');this.onStatus(p,'Fil terminé');return}if(!terminal){const q=this.constrain(last,p,free);if(q.x!==last.x||q.y!==last.y)this.pendingWire.points.push(q);this.preview=[...this.pendingWire.points];this.render();this.onStatus(q,'Point validé — poursuivez ou cliquez sur une borne')}}
 constrain(from,to,free=false){if(free)return to;return Math.abs(to.x-from.x)>=Math.abs(to.y-from.y)?{x:to.x,y:from.y}:{x:from.x,y:to.y}}
 normalizeRect(a,b){return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),width:Math.abs(b.x-a.x),height:Math.abs(b.y-a.y)}}
 itemsInRect(r){const inside=p=>p.x>=r.x&&p.x<=r.x+r.width&&p.y>=r.y&&p.y<=r.y+r.height,ids=[];for(const c of this.schematic.components){const junction=c.type==='junction',vertical=c.rotation%180!==0,halfW=junction?8:vertical?32:55,halfH=junction?8:vertical?55:32;if(c.position.x-halfW>=r.x&&c.position.x+halfW<=r.x+r.width&&c.position.y-halfH>=r.y&&c.position.y+halfH<=r.y+r.height)ids.push(c.id)}for(const w of this.schematic.wires)if(w.points.length&&w.points.every(inside))ids.push(w.id);return ids}
 terminalPosition(reference){const separator=reference.lastIndexOf(':'),component=this.schematic.getComponent(reference.slice(0,separator)),terminal=reference.slice(separator+1);if(!component)return null;let local={x:0,y:0};if(component.type!=='junction'){local.x=terminal==='A'||terminal==='OUT'||terminal==='COM'?-50:50;if(component.type==='contact'&&component.contactType==='CHANGEOVER')local.y=terminal==='NC'?-14:terminal==='NO'?14:0}const angle=component.rotation*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle);return{x:Math.round(component.position.x+local.x*cos-local.y*sin),y:Math.round(component.position.y+local.x*sin+local.y*cos)}}
 segmentOrientation(a,b){return Math.abs(b.x-a.x)>=Math.abs(b.y-a.y)?'H':'V'}
 moveWireEndpoint(wire,atStart,point){const index=atStart?0:wire.points.length-1,neighborIndex=atStart?1:wire.points.length-2,old=wire.points[index],neighbor=wire.points[neighborIndex],orientation=this.segmentOrientation(old,neighbor);if(wire.points.length===2){const other={...neighbor},bend=orientation==='H'?{x:other.x,y:point.y}:{x:point.x,y:other.y};wire.points=atStart?[point,bend,other]:[other,bend,point];return}wire.points[index]=point;if(orientation==='H')wire.points[neighborIndex].y=point.y;else wire.points[neighborIndex].x=point.x}
 syncConnectedWires(component){if(!component)return;for(const wire of this.schematic.wires){if(wire.from?.startsWith(`${component.id}:`)&&wire.points.length){const point=this.terminalPosition(wire.from);if(point)this.moveWireEndpoint(wire,true,point)}if(wire.to?.startsWith(`${component.id}:`)&&wire.points.length){const point=this.terminalPosition(wire.to);if(point)this.moveWireEndpoint(wire,false,point)}}}
 moveWirePoint(drag,point){const wire=this.schematic.getWire(drag.wireId),source=drag.originalPoints,index=drag.index;if(!wire||index<=0||index>=source.length-1)return;const prefix=source.slice(0,index).map(p=>({...p})),suffix=source.slice(index+1).map(p=>({...p})),previous=prefix.at(-1),next=suffix[0],before=drag.previousOrientation==='H'?{x:point.x,y:previous.y}:{x:previous.x,y:point.y},after=drag.nextOrientation==='H'?{x:next.x,y:point.y}:{x:point.x,y:next.y},same=(a,b)=>a.x===b.x&&a.y===b.y;const points=[...prefix];if(!same(before,previous)&&!same(before,point))points.push(before);const selectedIndex=points.length;points.push(point);if(!same(after,point)&&!same(after,next))points.push(after);wire.points=[...points,...suffix];this.selectedWirePoint=selectedIndex}
 deleteSelectedWirePoint(){const wire=this.schematic.getWire(this.selection),index=this.selectedWirePoint;if(!wire||index===null||index<=0||index>=wire.points.length-1)return false;this.snapshot();const previous=wire.points[index-1],next=wire.points[index+1];if(previous.x===next.x||previous.y===next.y)wire.points.splice(index,1);else wire.points.splice(index,1,{x:next.x,y:previous.y});this.selectedWirePoint=null;this.onChange('delete-wire-point');this.render();return true}
 pickPoint(message,callback){this.cancelAction();this.pointPicker=callback;this.onStatus(null,message)}
 cancelAction(){const hadAction=!!(this.pendingWire||this.drag||this.tool||this.pointPicker);this.pendingWire=null;this.preview=null;this.marquee=null;this.drag=null;this.tool=null;this.pointPicker=null;this.onCancel?.();this.render();this.onStatus(null,hadAction?'Action annulée':'Mode sélection')}
 selectMany(ids){this.selectedWirePoint=null;this.selections=new Set(ids);this.selection=ids.length===1?ids[0]:null;this.onSelect(this.selection,ids);this.render()}
 select(id){this.selectedWirePoint=null;this.selections=new Set(id?[id]:[]);this.selection=id;this.onSelect(id,id?[id]:[]);this.render()}
 related(){const set=new Set(),c=this.schematic.getComponent(this.selection);if(c?.type==='coil'){set.add(c.id);this.schematic.components.filter(x=>x.controllerId===c.id).forEach(x=>set.add(x.id))}if(c?.type==='contact'&&c.controllerId){set.add(c.id);set.add(c.controllerId);this.schematic.components.filter(x=>x.controllerId===c.controllerId).forEach(x=>set.add(x.id))}return set}
 render(simulation=this.simulation){this.simulation=simulation;this.renderer.render(this.schematic,{selection:this.selection,selections:this.selections,selectedWirePoint:this.selectedWirePoint,related:this.related(),simulation,wirePreview:this.preview,marquee:this.marquee})}
 setMode(m){this.mode=m;this.pendingWire=null;this.preview=null;this.marquee=null;this.render()}
 wheel(e){e.preventDefault();const before=this.point(e),factor=e.deltaY<0?1.12:.89;this.scale=Math.min(3,Math.max(.25,this.scale*factor));const r=this.svg.getBoundingClientRect();this.pan.x=e.clientX-r.left-before.x*this.scale;this.pan.y=e.clientY-r.top-before.y*this.scale;this.applyTransform();this.onStatus(null,`${Math.round(this.scale*100)} %`)}
 resetView(){this.scale=1;this.pan={x:0,y:Math.max(0,this.svg.clientHeight)-gridExtent(this.schematic.grid.referenceGrid).height};this.applyTransform()}
 zoom(f){if(f===0)this.resetView();else{this.scale=Math.min(3,Math.max(.25,this.scale*f));this.applyTransform()}}
 applyTransform(){this.svg.querySelector('#viewport').setAttribute('transform',`translate(${this.pan.x} ${this.pan.y}) scale(${this.scale})`);this.onViewportChange?.({pan:{...this.pan},scale:this.scale})}
 key(e,down){if(e.code==='Space'){this.space=down;if(down)e.preventDefault()}if(!down||['INPUT','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='Delete'&&this.selectedWirePoint!==null){this.deleteSelectedWirePoint();return}if(e.key==='Delete'&&this.selections.size)this.remove();if(e.key.toLowerCase()==='r'&&this.selection)this.rotate();if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();this.undo()}if(e.ctrlKey&&(e.key.toLowerCase()==='y'||e.shiftKey&&e.key.toLowerCase()==='z')){e.preventDefault();this.redo()}if(e.ctrlKey&&e.key.toLowerCase()==='d'){e.preventDefault();this.duplicate()}}
 snapshot(){this.history.push(JSON.stringify(this.schematic.toJSON()));if(this.history.length>60)this.history.shift();this.future=[]}
 restore(raw){this.schematic=new Schematic(JSON.parse(raw));this.selection=null;this.selections.clear();this.onChange('restore',this.schematic)}
 undo(){if(!this.history.length)return;this.future.push(JSON.stringify(this.schematic.toJSON()));this.restore(this.history.pop())}redo(){if(!this.future.length)return;this.history.push(JSON.stringify(this.schematic.toJSON()));this.restore(this.future.pop())}
 remove(){this.snapshot();for(const id of this.selections)this.schematic.remove(id);this.select(null);this.onChange('delete')}
 rotate(){const c=this.schematic.getComponent(this.selection);if(c){this.snapshot();c.rotation=(c.rotation+90)%360;this.syncConnectedWires(c);this.onChange('rotate')}}
 duplicate(){const c=this.schematic.getComponent(this.selection);if(!c)return;this.snapshot();const d=JSON.parse(JSON.stringify(c));d.id=this.schematic.nextId(c.type==='coil'?'R':c.type==='contact'?'SW':c.type==='powerSource'?'PS':'J');d.position={x:c.position.x+30,y:c.position.y+30};this.schematic.addComponent(d);this.select(d.id);this.onChange('duplicate')}
}
