import {PowerSource,Coil,Contact,Junction} from '../model/components.js';import {WireStyle} from '../model/Wire.js';
export class Editor{
 constructor({svg,schematic,renderer,onChange,onSelect,onStatus}){Object.assign(this,{svg,schematic,renderer,onChange,onSelect,onStatus});this.mode='EDIT';this.tool=null;this.styleId='RED';this.selection=null;this.scale=1;this.pan={x:0,y:0};this.history=[];this.future=[];this.space=false;this.bind();this.applyTransform()}
 setSchematic(s){this.schematic=s;this.selection=null;this.history=[];this.future=[];this.render()}
 bind(){this.svg.addEventListener('pointerdown',e=>this.down(e));this.svg.addEventListener('pointermove',e=>this.move(e));this.svg.addEventListener('pointerup',e=>this.up(e));this.svg.addEventListener('wheel',e=>this.wheel(e),{passive:false});window.addEventListener('keydown',e=>this.key(e,true));window.addEventListener('keyup',e=>this.key(e,false))}
 point(e){const r=this.svg.getBoundingClientRect();return {x:(e.clientX-r.left-this.pan.x)/this.scale,y:(e.clientY-r.top-this.pan.y)/this.scale}}
 snap(p){const g=this.schematic.grid.snapGrid;if(!g.enabled)return p;return{x:Math.round(p.x/g.stepX)*g.stepX,y:Math.round(p.y/g.stepY)*g.stepY}}
 down(e){this.svg.focus();const p=this.snap(this.point(e)),terminal=e.target.dataset.terminal,id=e.target.closest('[data-id]')?.dataset.id;if(e.button===1||this.space){this.drag={kind:'pan',start:{x:e.clientX,y:e.clientY},origin:{...this.pan}};this.svg.setPointerCapture(e.pointerId);return}if(this.mode==='SIMULATION'){const c=this.schematic.getComponent(id);if(c?.type==='contact'&&c.controlType==='manual'){c.manualActivated=!c.manualActivated;this.onChange('simulation')}return}if(this.tool==='wire'){if(terminal)this.wireClick(terminal,p,e.shiftKey);return}if(this.tool&&!id){this.snapshot();this.add(this.tool,p);return}if(id){this.select(id);const c=this.schematic.getComponent(id);if(c){this.snapshot();this.drag={kind:'component',id,offset:{x:p.x-c.position.x,y:p.y-c.position.y}};this.svg.setPointerCapture(e.pointerId)}}else this.select(null)}
 move(e){const p=this.point(e);this.onStatus(this.snap(p));if(this.drag?.kind==='pan'){this.pan={x:this.drag.origin.x+e.clientX-this.drag.start.x,y:this.drag.origin.y+e.clientY-this.drag.start.y};this.applyTransform()}if(this.drag?.kind==='component'){const c=this.schematic.getComponent(this.drag.id),q=this.snap({x:p.x-this.drag.offset.x,y:p.y-this.drag.offset.y});c.position=q;this.render()}if(this.pendingWire){const q=this.snap(p),a=this.pendingWire.point;this.preview=e.shiftKey?[a,q]:[a,{x:q.x,y:a.y},q];this.render()}}
 up(){if(this.drag?.kind==='component')this.onChange('move');this.drag=null}
 add(tool,p){let c;if(tool==='powerSource')c=new PowerSource({id:this.schematic.nextId('PS'),label:'Alimentation 24 VAC',position:p});if(tool==='coil')c=new Coil({id:this.schematic.nextId('R'),label:'RELAY',position:p});if(tool==='contactNO'||tool==='contactNC')c=new Contact({id:this.schematic.nextId('SW'),label:tool==='contactNO'?'CONTACT NO':'CONTACT NC',position:p,contactType:tool==='contactNO'?'NO':'NC'});if(tool==='junction')c=new Junction({id:this.schematic.nextId('J'),label:'',position:p});if(c){this.schematic.components.push(c);this.select(c.id);this.onChange('add')}}
 wireClick(terminal,p,free){if(!this.pendingWire){this.pendingWire={terminal,point:p};this.preview=[p,p];this.onStatus(p,'Cliquez sur la borne d’arrivée')}else if(terminal!==this.pendingWire.terminal){this.snapshot();const points=free?[this.pendingWire.point,p]:[this.pendingWire.point,{x:p.x,y:this.pendingWire.point.y},p];const w={id:this.schematic.nextId('W'),styleId:this.styleId,from:this.pendingWire.terminal,to:terminal,points};this.schematic.addWire(w);this.pendingWire=null;this.preview=null;this.select(w.id);this.onChange('wire')}}
 select(id){this.selection=id;this.onSelect(id);this.render()}
 related(){const set=new Set(),c=this.schematic.getComponent(this.selection);if(c?.type==='coil'){set.add(c.id);this.schematic.components.filter(x=>x.controllerId===c.id).forEach(x=>set.add(x.id))}if(c?.type==='contact'&&c.controllerId){set.add(c.id);set.add(c.controllerId);this.schematic.components.filter(x=>x.controllerId===c.controllerId).forEach(x=>set.add(x.id))}return set}
 render(simulation=this.simulation){this.simulation=simulation;this.renderer.render(this.schematic,{selection:this.selection,related:this.related(),simulation,wirePreview:this.preview})}
 setMode(m){this.mode=m;this.pendingWire=null;this.preview=null;this.render()}
 wheel(e){e.preventDefault();const before=this.point(e),factor=e.deltaY<0?1.12:.89;this.scale=Math.min(3,Math.max(.25,this.scale*factor));const r=this.svg.getBoundingClientRect();this.pan.x=e.clientX-r.left-before.x*this.scale;this.pan.y=e.clientY-r.top-before.y*this.scale;this.applyTransform();this.onStatus(null,`${Math.round(this.scale*100)} %`)}
 zoom(f){if(f===0){this.scale=1;this.pan={x:0,y:0}}else this.scale=Math.min(3,Math.max(.25,this.scale*f));this.applyTransform()}
 applyTransform(){this.svg.querySelector('#viewport').setAttribute('transform',`translate(${this.pan.x} ${this.pan.y}) scale(${this.scale})`)}
 key(e,down){if(e.code==='Space'){this.space=down;if(down)e.preventDefault()}if(!down||['INPUT','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='Delete'&&this.selection)this.remove();if(e.key.toLowerCase()==='r'&&this.selection)this.rotate();if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();this.undo()}if(e.ctrlKey&&(e.key.toLowerCase()==='y'||e.shiftKey&&e.key.toLowerCase()==='z')){e.preventDefault();this.redo()}if(e.ctrlKey&&e.key.toLowerCase()==='d'){e.preventDefault();this.duplicate()}}
 snapshot(){this.history.push(JSON.stringify(this.schematic.toJSON()));if(this.history.length>60)this.history.shift();this.future=[]}
 restore(raw){import('../model/Schematic.js').then(({Schematic})=>{this.schematic=new Schematic(JSON.parse(raw));this.selection=null;this.onChange('restore',this.schematic)})}
 undo(){if(!this.history.length)return;this.future.push(JSON.stringify(this.schematic.toJSON()));this.restore(this.history.pop())}redo(){if(!this.future.length)return;this.history.push(JSON.stringify(this.schematic.toJSON()));this.restore(this.future.pop())}
 remove(){this.snapshot();this.schematic.remove(this.selection);this.select(null);this.onChange('delete')}
 rotate(){const c=this.schematic.getComponent(this.selection);if(c){this.snapshot();c.rotation=(c.rotation+90)%360;this.onChange('rotate')}}
 duplicate(){const c=this.schematic.getComponent(this.selection);if(!c)return;this.snapshot();const d=JSON.parse(JSON.stringify(c));d.id=this.schematic.nextId(c.type==='coil'?'R':c.type==='contact'?'SW':c.type==='powerSource'?'PS':'J');d.position={x:c.position.x+30,y:c.position.y+30};this.schematic.addComponent(d);this.select(d.id);this.onChange('duplicate')}
}
