import test from 'node:test';import assert from 'node:assert/strict';import {createExample} from '../src/model/example.js';import {CircuitSolver} from '../src/simulation/CircuitSolver.js';import {SchematicSerializer} from '../src/persistence/SchematicSerializer.js';
import {Schematic} from '../src/model/Schematic.js';
test('le relais en cascade reste éteint quand START est ouvert',()=>{const s=createExample(),r=new CircuitSolver().solve(s);assert.deepEqual(r.poweredCoils,[]);assert.equal(r.converged,true)});
test('START alimente R1 puis son contact alimente R2',()=>{const s=createExample();s.getComponent('START').manualActivated=true;const r=new CircuitSolver().solve(s);assert.deepEqual(new Set(r.poweredCoils),new Set(['R1','R2']));assert.ok(r.iterations>=2);assert.equal(r.converged,true)});
test('un contact de relais maintient sa bobine après le relâchement du bouton de départ',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'START',type:'contact',contactType:'NO',controlType:'manual',manualActivated:true},{id:'HOLD',type:'contact',contactType:'NO',controlType:'coil',controllerId:'LOCK.RE'},{id:'LOCK.RE',type:'coil'},{id:'J1',type:'junction'},{id:'J2',type:'junction'}],wires:[{id:'W1',from:'PS1:OUT',to:'J1:J',points:[]},{id:'W2',from:'J1:J',to:'START:A',points:[]},{id:'W3',from:'START:B',to:'J2:J',points:[]},{id:'W4',from:'J1:J',to:'HOLD:A',points:[]},{id:'W5',from:'HOLD:B',to:'J2:J',points:[]},{id:'W6',from:'J2:J',to:'LOCK.RE:A',points:[]},{id:'W7',from:'LOCK.RE:B',to:'PS1:RETURN',points:[]}]});const solver=new CircuitSolver();let result=solver.solve(s);assert.deepEqual(result.poweredCoils,['LOCK.RE']);s.getComponent('START').manualActivated=false;result=solver.solve(s,result.activatedCoils);assert.deepEqual(result.poweredCoils,['LOCK.RE']);assert.equal(result.converged,true);s.getComponent('PS1').outputs[0].enabled=false;result=solver.solve(s,result.activatedCoils);assert.deepEqual(result.poweredCoils,[])});
test('le format JSON conserve les relations logiques',()=>{const s=createExample(),copy=SchematicSerializer.parse(SchematicSerializer.stringify(s));assert.equal(copy.getComponent('R1.1').controllerId,'R1');assert.equal(copy.formatVersion,2)});
test('renommer un relais accepte les espaces et conserve fils et contacts associés',()=>{const s=createExample();s.renameComponent('R1','Relais principal 25 A');assert.ok(s.getComponent('Relais principal 25 A'));assert.ok(s.wires.some(w=>w.from==='Relais principal 25 A:B'||w.to==='Relais principal 25 A:B'));assert.equal(s.getComponent('R1.1').controllerId,'Relais principal 25 A')});
test('tous les composants et les fils peuvent être renommés sans doublon',()=>{const s=createExample();s.renameComponent('START','Bouton gauche');assert.ok(s.getComponent('Bouton gauche'));assert.ok(s.wires.some(w=>w.from==='Bouton gauche:B'||w.to==='Bouton gauche:A'));s.renameWire('W1','Alimentation principale');assert.ok(s.getWire('Alimentation principale'));assert.throws(()=>s.renameComponent('R1','Alimentation principale'),/déjà utilisé/)});
test('le format JSON conserve les informations, grilles et le calque PDF',()=>{const s=createExample();s.name='Jackpot';s.brand='Williams';s.year=1971;s.grid.snapGrid.stepX=5;s.grid.referenceGrid.cellWidth=180;s.background={name:'plan.pdf',mimeType:'application/pdf',dataUrl:'data:application/pdf;base64,JVBERg==',visible:true,opacity:35,x:20,y:40,width:1400,height:900};const copy=SchematicSerializer.parse(SchematicSerializer.stringify(s));assert.equal(copy.name,'Jackpot');assert.equal(copy.brand,'Williams');assert.equal(copy.year,1971);assert.equal(copy.grid.snapGrid.stepX,5);assert.equal(copy.grid.referenceGrid.cellWidth,180);assert.deepEqual(copy.background,s.background)});

test('ouvrir et sauvegarder partagent le même dossier de projets',async()=>{const original=globalThis.window,openCalls=[],saveCalls=[];const fileHandle={name:'projet.ipcsx',getFile:async()=>({name:'projet.ipcs',text:async()=>SchematicSerializer.stringify(createExample())}),createWritable:async()=>({write:async()=>{},close:async()=>{}})};globalThis.window={showOpenFilePicker:async options=>{openCalls.push(options);return[fileHandle]},showSaveFilePicker:async options=>{saveCalls.push(options);return fileHandle}};try{await SchematicSerializer.save(createExample());await SchematicSerializer.open();assert.equal(openCalls[0].id,'ipcs-projects-v2');assert.equal(openCalls[0].startIn,'documents')}finally{globalThis.window=original}});

test('sauvegarder écrase un IPCSX chargé et propose le dossier d’un ancien IPCS',async()=>{const original=globalThis.window,pickerCalls=[],writes=[],ipcsxHandle={name:'jackpot.ipcsx',createWritable:async()=>({write:async data=>writes.push(data),close:async()=>{}})},legacyHandle={name:'jackpot.ipcs'},newHandle={name:'jackpot.ipcsx',createWritable:async()=>({write:async()=>{},close:async()=>{}})};globalThis.window={showSaveFilePicker:async options=>{pickerCalls.push(options);return newHandle}};try{assert.equal(await SchematicSerializer.save(createExample(),ipcsxHandle),ipcsxHandle);assert.equal(pickerCalls.length,0);assert.equal(writes.length,1);assert.equal(await SchematicSerializer.save(createExample(),legacyHandle),newHandle);assert.equal(pickerCalls[0].startIn,legacyHandle);assert.match(pickerCalls[0].suggestedName,/\.ipcsx$/)}finally{globalThis.window=original}});

test('le conteneur IPCSX sépare le fond PDF et restaure les réseaux',()=>{const s=createExample();s.background={name:'fond.pdf',mimeType:'application/pdf',dataUrl:'data:application/pdf;base64,JVBERg==',visible:true,opacity:50};const packed=SchematicSerializer.pack(s),copy=SchematicSerializer.unpack(packed.buffer);assert.equal(SchematicSerializer.fileName(s).endsWith('.ipcsx'),true);assert.equal(copy.formatVersion,2);assert.equal(copy.background.dataUrl,s.background.dataUrl);assert.equal(copy.wires.length,s.wires.length);assert.ok(copy.networks.length>0)});

test('la migration réseau conserve l’ordre et toutes les portions de fils',()=>{const original=createExample(),copy=new Schematic(original.toV2JSON());assert.deepEqual(copy.wires.map(wire=>wire.id),original.wires.map(wire=>wire.id));assert.deepEqual(copy.wires.map(wire=>wire.points),original.wires.map(wire=>wire.points));assert.equal(copy.networks.flatMap(network=>network.segments).length,original.wires.length)});

test('un contact NC auto-commandé coupe le courant après lui et signale une oscillation',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',label:'24 VAC',position:{x:0,y:0},outputs:[{id:'OUT',enabled:true}]},{id:'SW1',type:'contact',contactType:'NC',controlType:'coil',controllerId:'R2',label:'SW1',position:{x:100,y:0}},{id:'R2',type:'coil',label:'R2',position:{x:200,y:0}}],wires:[{id:'W1',from:'PS1:OUT',to:'SW1:A',points:[{x:0,y:0},{x:50,y:0}]},{id:'W2',from:'SW1:B',to:'R2:A',points:[{x:150,y:0},{x:150,y:0}]},{id:'W3',from:'R2:B',to:'PS1:RETURN',points:[{x:250,y:0},{x:0,y:0}]}]});const result=new CircuitSolver().solve(s);assert.equal(result.oscillating,true);assert.deepEqual(result.poweredCoils,[]);assert.ok(result.activatedCoils.includes('R2'));assert.ok(result.poweredWires.includes('W1'));assert.ok(result.poweredWires.includes('W3'));assert.ok(!result.poweredWires.includes('W2'))});

test('un contact inverseur alimente alternativement ses sorties NC et NO',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',position:{x:0,y:0},outputs:[{id:'OUT',enabled:true}]},{id:'SW1',type:'contact',contactType:'CHANGEOVER',controlType:'manual',position:{x:100,y:0}},{id:'L1',type:'lamp',label:'Lampe',position:{x:200,y:-20}},{id:'M1',type:'motor',label:'Moteur',position:{x:200,y:20}}],wires:[{id:'W1',from:'PS1:OUT',to:'SW1:COM',points:[]},{id:'W2',from:'SW1:NC',to:'L1:A',points:[]},{id:'W3',from:'L1:B',to:'PS1:RETURN',points:[]},{id:'W4',from:'SW1:NO',to:'M1:A',points:[]},{id:'W5',from:'M1:B',to:'PS1:RETURN',points:[]}]});let result=new CircuitSolver().solve(s);assert.ok(result.poweredComponents.includes('L1'));assert.ok(!result.poweredComponents.includes('M1'));s.getComponent('SW1').manualActivated=true;result=new CircuitSolver().solve(s);assert.ok(!result.poweredComponents.includes('L1'));assert.ok(result.poweredComponents.includes('M1'));const inverseur=s.getComponent('SW1');inverseur.commonAlignment='NO';inverseur.manualActivated=false;result=new CircuitSolver().solve(s);assert.ok(!result.poweredComponents.includes('L1'));assert.ok(result.poweredComponents.includes('M1'));inverseur.manualActivated=true;result=new CircuitSolver().solve(s);assert.ok(result.poweredComponents.includes('L1'));assert.ok(!result.poweredComponents.includes('M1'));assert.equal(s.getComponent('L1').label,'Lampe');assert.equal(s.getComponent('L1').number,undefined)});

test('un fusible grillé ouvre le circuit',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'F1',type:'fuse',rating:'10 A'},{id:'R1',type:'coil'}],wires:[{id:'W1',from:'PS1:OUT',to:'F1:A',points:[]},{id:'W2',from:'F1:B',to:'R1:A',points:[]},{id:'W3',from:'R1:B',to:'PS1:RETURN',points:[]}]});assert.deepEqual(new CircuitSolver().solve(s).poweredCoils,['R1']);s.getComponent('F1').blown=true;assert.deepEqual(new CircuitSolver().solve(s).poweredCoils,[])});

test('un relais est en surbrillance seulement si ses deux bornes ferment le circuit',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'R1',type:'coil'}],wires:[{id:'W1',from:'PS1:OUT',to:'R1:A',points:[]},{id:'W2',from:'R1:B',to:'PS1:RETURN',points:[]}]});const solver=new CircuitSolver();let result=solver.solve(s);assert.ok(result.poweredCoils.includes('R1'));assert.ok(result.poweredComponents.includes('R1'));s.wires=s.wires.filter(wire=>wire.id!=='W2');result=solver.solve(s);assert.ok(!result.poweredCoils.includes('R1'));assert.ok(!result.poweredComponents.includes('R1'))});

test('un ADJ TIP relie chaque Tip uniquement à la ligne sélectionnée',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'ADJ1',type:'adjTip',rows:2,multipleTips:false,tipPositions:[2]},{id:'L1',type:'lamp'}],wires:[{id:'W1',from:'PS1:OUT',to:'ADJ1:TIP1',points:[]},{id:'W2',from:'ADJ1:LINE2',to:'L1:A',points:[]},{id:'W3',from:'L1:B',to:'PS1:RETURN',points:[]}]});const solver=new CircuitSolver();assert.ok(solver.solve(s).poweredComponents.includes('L1'));s.getComponent('ADJ1').tipPositions[0]=0;assert.ok(!solver.solve(s).poweredComponents.includes('L1'))});

test('un ADJ TIP conserve sa hauteur compacte et les valeurs personnalisées des lignes',()=>{const s=new Schematic({components:[{id:'ADJ1',type:'adjTip',rows:4,heightCells:2,lineLabels:['1000','2000','3000','EXTRA']}]}),adj=s.getComponent('ADJ1');assert.equal(adj.heightCells,2);assert.deepEqual(adj.lineLabels,['1000','2000','3000','EXTRA'])});

test('un ADJ TIP utilise une hauteur d’une case et une orientation horizontale par défaut',()=>{const adj=new Schematic({components:[{id:'ADJ1',type:'adjTip'}]}).getComponent('ADJ1');assert.equal(adj.heightCells,1);assert.equal(adj.rotation,0)});

test('un connecteur distant conduit le courant sans fil visible entre ses deux extrémités',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'CD1-E',type:'remoteConnector',linkedId:'CD1-S',direction:'in'},{id:'CD1-S',type:'remoteConnector',linkedId:'CD1-E',direction:'out'},{id:'L1',type:'lamp'}],wires:[{id:'W1',from:'PS1:OUT',to:'CD1-E:J',points:[]},{id:'W2',from:'CD1-S:J',to:'L1:A',points:[]},{id:'W3',from:'L1:B',to:'PS1:RETURN',points:[]}]});const result=new CircuitSolver().solve(s);assert.ok(result.poweredComponents.includes('L1'));assert.equal(s.wires.length,3)});

test('un compteur avance une seule fois par impulsion et ferme le contact de sa position',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true},{id:'PULSE',enabled:true},{id:'RESET',enabled:false}]},{id:'INC',type:'coil'},{id:'RST',type:'coil'},{id:'CTR1',type:'counter',positions:4,currentPosition:1,incrementRelayId:'INC',resetRelayId:'RST'},{id:'L1',type:'lamp'}],wires:[{id:'W1',from:'PS1:PULSE',to:'INC:A',points:[]},{id:'W2',from:'INC:B',to:'PS1:RETURN',points:[]},{id:'W3',from:'PS1:RESET',to:'RST:A',points:[]},{id:'W4',from:'RST:B',to:'PS1:RETURN',points:[]},{id:'W5',from:'PS1:OUT',to:'CTR1:P2A',points:[]},{id:'W6',from:'CTR1:P2B',to:'L1:A',points:[]},{id:'W7',from:'L1:B',to:'PS1:RETURN',points:[]}]});const solver=new CircuitSolver(),counter=s.getComponent('CTR1'),pulse=s.getComponent('PS1').outputs.find(output=>output.id==='PULSE'),reset=s.getComponent('PS1').outputs.find(output=>output.id==='RESET');let result=solver.step(s);assert.equal(counter.currentPosition,2);assert.ok(result.poweredComponents.includes('L1'));solver.step(s,result.poweredCoils);assert.equal(counter.currentPosition,2);pulse.enabled=false;result=solver.step(s,result.poweredCoils);pulse.enabled=true;result=solver.step(s,result.poweredCoils);assert.equal(counter.currentPosition,3);pulse.enabled=false;reset.enabled=true;result=solver.step(s,result.poweredCoils);assert.equal(counter.currentPosition,1)});

test('une position de compteur désactivée ne ferme pas son contact',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'CTR1',type:'counter',positions:2,currentPosition:2,switchPositions:[true,false]},{id:'L1',type:'lamp'}],wires:[{id:'W1',from:'PS1:OUT',to:'CTR1:P2A',points:[]},{id:'W2',from:'CTR1:P2B',to:'L1:A',points:[]},{id:'W3',from:'L1:B',to:'PS1:RETURN',points:[]}]});assert.ok(!new CircuitSolver().solve(s).poweredComponents.includes('L1'))});

test('un compteur appuie le contact SW associé à sa position',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'CTR1',type:'counter',positions:2,currentPosition:2,positionContactIds:[null,'SW1']},{id:'SW1',type:'contact',controlMode:'SW',contactType:'NO'},{id:'L1',type:'lamp'}],wires:[{id:'W1',from:'PS1:OUT',to:'SW1:A',points:[]},{id:'W2',from:'SW1:B',to:'L1:A',points:[]},{id:'W3',from:'L1:B',to:'PS1:RETURN',points:[]}]});assert.ok(new CircuitSolver().solve(s).poweredComponents.includes('L1'));s.getComponent('CTR1').currentPosition=1;assert.ok(!new CircuitSolver().solve(s).poweredComponents.includes('L1'))});

test('un transformateur alimente ses deux phases secondaires par rapport au neutre central',()=>{const s=new Schematic({components:[{id:'PS1',type:'powerSource',outputs:[{id:'OUT',enabled:true}]},{id:'T1',type:'transformer'},{id:'L1',type:'lamp'},{id:'M1',type:'motor'}],wires:[{id:'W1',from:'PS1:OUT',to:'T1:P1',points:[]},{id:'W2',from:'T1:P2',to:'PS1:RETURN',points:[]},{id:'W3',from:'T1:S1',to:'L1:A',points:[]},{id:'W4',from:'L1:B',to:'T1:S2',points:[]},{id:'W5',from:'T1:S3',to:'M1:A',points:[]},{id:'W6',from:'M1:B',to:'T1:S2',points:[]}]});const transformer=s.getComponent('T1');assert.equal(transformer.terminals.find(t=>t.id==='S2').kind,'neutral');assert.equal(transformer.terminals.find(t=>t.id==='S1').kind,'phase');assert.equal(transformer.terminals.find(t=>t.id==='S3').kind,'phase');let result=new CircuitSolver().solve(s);assert.ok(result.poweredComponents.includes('T1'));assert.ok(result.poweredComponents.includes('L1'));assert.ok(result.poweredComponents.includes('M1'));s.getComponent('PS1').outputs[0].enabled=false;result=new CircuitSolver().solve(s);assert.ok(!result.poweredComponents.includes('L1'));assert.ok(!result.poweredComponents.includes('M1'))});
