import test from 'node:test';
import assert from 'node:assert/strict';
import {Editor} from '../src/editor/Editor.js';
import {Schematic} from '../src/model/Schematic.js';
import {SvgRenderer} from '../src/rendering/SvgRenderer.js';
import {PropertyPanel} from '../src/ui/PropertyPanel.js';

function editorStub(){const editor=Object.create(Editor.prototype);editor.schematic=new Schematic();editor.styleId='RED';editor.wireDescription='';editor.selections=new Set();editor.selectedWirePoint=null;editor.render=()=>{};editor.onStatus=()=>{};editor.snapshot=()=>{};editor.onSelect=()=>{};editor.onChange=()=>{};return editor}
const isOrthogonal=wire=>wire.points.slice(1).every((point,index)=>point.x===wire.points[index].x||point.y===wire.points[index].y);

test('chaque clic ajoute un point orthogonal et une borne termine le fil',()=>{const editor=editorStub();editor.wireClick('A:OUT',{x:0,y:0},false);editor.wireClick(null,{x:40,y:30},false);editor.wireClick(null,{x:60,y:80},false);editor.wireClick('B:A',{x:100,y:100},false);assert.deepEqual(editor.schematic.wires[0].points,[{x:0,y:0},{x:40,y:0},{x:40,y:80},{x:100,y:80},{x:100,y:100}]);assert.equal(editor.schematic.wires[0].id,'Rouge-W1');assert.equal(editor.pendingWire,null)});

test('la description saisie est enregistrée sur le nouveau fil',()=>{const editor=editorStub();editor.wireDescription='Alimentation bobine gauche';editor.wireClick('A:OUT',{x:0,y:0},false);editor.wireClick('B:A',{x:100,y:0},false);assert.equal(editor.schematic.wires[0].description,'Alimentation bobine gauche')});

test('le clic libre avec Maj conserve les coordonnées exactes',()=>{const editor=editorStub();editor.wireClick('A:OUT',{x:0,y:0},false);editor.wireClick(null,{x:25,y:35},true);assert.deepEqual(editor.pendingWire.points,[{x:0,y:0},{x:25,y:35}])});

test('le rectangle ne retient que les éléments complètement contenus',()=>{const editor=editorStub();editor.schematic.addComponent({id:'R1',type:'coil',label:'dedans',position:{x:100,y:100},rotation:0,terminals:[]});editor.schematic.addComponent({id:'R2',type:'coil',label:'partiel',position:{x:190,y:100},rotation:0,terminals:[]});editor.schematic.addWire({id:'W1',from:'A:X',to:'B:X',points:[{x:20,y:20},{x:180,y:180}]});editor.schematic.addWire({id:'W2',from:'A:Y',to:'B:Y',points:[{x:20,y:20},{x:220,y:180}]});assert.deepEqual(editor.itemsInRect({x:0,y:0,width:200,height:200}),['R1','W1'])});

test('les extrémités suivent le composant en restant orthogonales',()=>{const editor=editorStub();const coil=editor.schematic.addComponent({id:'R1',type:'coil',label:'relais',position:{x:100,y:100},rotation:0});editor.schematic.addWire({id:'W1',from:'R1:A',to:'X:A',points:[{x:50,y:100},{x:0,y:100}]});editor.schematic.addWire({id:'W2',from:'X:B',to:'R1:B',points:[{x:0,y:120},{x:150,y:100}]});coil.position={x:200,y:150};editor.syncConnectedWires(coil);assert.deepEqual(editor.schematic.getWire('W1').points[0],{x:150,y:150});assert.deepEqual(editor.schematic.getWire('W2').points.at(-1),{x:250,y:150});assert.ok(editor.schematic.wires.every(isOrthogonal));coil.rotation=90;editor.syncConnectedWires(coil);assert.deepEqual(editor.schematic.getWire('W1').points[0],{x:200,y:100});assert.deepEqual(editor.schematic.getWire('W2').points.at(-1),{x:200,y:200});assert.ok(editor.schematic.wires.every(isOrthogonal))});

test('un fil peut être sélectionné directement',()=>{const editor=editorStub();editor.select('W1');assert.equal(editor.selection,'W1');assert.deepEqual([...editor.selections],['W1'])});

test('déplacer puis supprimer un sommet garde les extrémités et les segments orthogonaux',()=>{const editor=editorStub();const wire=editor.schematic.addWire({id:'W1',from:'A:X',to:'B:X',points:[{x:0,y:0},{x:100,y:0},{x:100,y:100}]});const drag={wireId:'W1',index:1,originalPoints:wire.points.map(p=>({...p})),previousOrientation:'H',nextOrientation:'V'};editor.moveWirePoint(drag,{x:60,y:40});assert.deepEqual(wire.points[0],{x:0,y:0});assert.deepEqual(wire.points.at(-1),{x:100,y:100});assert.ok(isOrthogonal(wire));editor.selection='W1';editor.selectedWirePoint=2;assert.equal(editor.deleteSelectedWirePoint(),true);assert.ok(isOrthogonal(wire))});

test('supprimer un sommet diagonal recrée le coude nécessaire',()=>{const editor=editorStub();const wire=editor.schematic.addWire({id:'W1',from:'A:X',to:'B:X',points:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:200,y:100}]});editor.selection='W1';editor.selectedWirePoint=1;editor.deleteSelectedWirePoint();assert.ok(isOrthogonal(wire));assert.deepEqual(wire.points[0],{x:0,y:0});assert.deepEqual(wire.points.at(-1),{x:200,y:100})});

test('les cinq bornes du transformateur sont sur la grille et suivent sa rotation',()=>{const editor=editorStub();editor.schematic.addComponent({id:'T1',type:'transformer',position:{x:100,y:100},rotation:0});assert.deepEqual(editor.terminalPosition('T1:P1'),{x:50,y:-25});assert.deepEqual(editor.terminalPosition('T1:S2'),{x:150,y:100});editor.schematic.getComponent('T1').rotation=90;assert.deepEqual(editor.terminalPosition('T1:P1'),{x:225,y:50});assert.deepEqual(editor.terminalPosition('T1:S2'),{x:100,y:150})});
test('la hauteur ADJ concerne le rectangle et toutes ses jonctions restent sur la grille',()=>{const editor=editorStub();editor.schematic.grid.snapGrid={enabled:true,visible:true,stepX:25,stepY:25};const adj=editor.schematic.addComponent({id:'ADJ1',type:'adjTip',position:{x:100,y:100},rotation:0,rows:2,heightCells:1});assert.deepEqual(editor.terminalPosition('ADJ1:LINE1'),{x:75,y:100});assert.deepEqual(editor.terminalPosition('ADJ1:LINE2'),{x:75,y:125});assert.deepEqual(editor.terminalPosition('ADJ1:TIP1'),{x:150,y:100});const original=globalThis.document;globalThis.document={createElementNS:(_ns,tag)=>({tag,attributes:{},children:[],setAttribute(name,value){this.attributes[name]=String(value)},append(...nodes){this.children.push(...nodes)}})};try{const renderer=Object.create(SvgRenderer.prototype),nodes=renderer.symbol(adj,{simulation:null},editor.schematic),main=nodes[0],tip=nodes.find(node=>node.attributes['data-adj-tip']!==undefined);assert.equal(main.tag,'rect');assert.equal(main.attributes.width,'25');assert.ok(Number(tip.attributes.x)>=Number(main.attributes.x)+Number(main.attributes.width));assert.equal(nodes.filter(node=>node.tag==='line').length,3);adj.tipPositions=[1];assert.equal(renderer.symbol(adj,{simulation:null},editor.schematic).filter(node=>node.tag==='line').length,4);adj.rows='3';adj.lineLabels=['1','2','3'];assert.equal(renderer.symbol(adj,{simulation:null},editor.schematic)[0].attributes.height,'100')}finally{globalThis.document=original}});

test('un ADJ peut espacer ses jonctions de deux cases',()=>{const editor=editorStub(),adj=editor.schematic.addComponent({id:'ADJ1',type:'adjTip',position:{x:100,y:100},rotation:0,rows:3,rowSpacingCells:2});assert.equal(adj.rowSpacingCells,2);assert.deepEqual(editor.terminalPosition('ADJ1:LINE1'),{x:75,y:50});assert.deepEqual(editor.terminalPosition('ADJ1:LINE3'),{x:75,y:150})});

test('placer un connecteur distant crée une paire liée sur la grille',()=>{const editor=editorStub();editor.add('remoteConnector',{x:100,y:125});const [incoming,outgoing]=editor.schematic.components;assert.equal(incoming.id,'CD1-E');assert.equal(outgoing.id,'CD1-S');assert.equal(incoming.linkedId,outgoing.id);assert.equal(outgoing.linkedId,incoming.id);assert.equal(incoming.styleId,'RED');assert.deepEqual(editor.terminalPosition(`${incoming.id}:J`),incoming.position);assert.deepEqual(outgoing.position,{x:200,y:125});editor.schematic.remove(incoming.id);assert.equal(editor.schematic.components.length,0)});

test('un inverseur sépare l’inversion des sorties de celle de l’alimentation',()=>{const editor=editorStub();const contact=editor.schematic.addComponent({id:'SW1',type:'contact',contactType:'CHANGEOVER',position:{x:100,y:100},rotation:0});assert.deepEqual(editor.terminalPosition('SW1:COM'),{x:50,y:100});assert.deepEqual(editor.terminalPosition('SW1:NC'),{x:150,y:100});assert.deepEqual(editor.terminalPosition('SW1:NO'),{x:150,y:125});contact.commonAlignment='NO';assert.deepEqual(editor.terminalPosition('SW1:COM'),{x:50,y:125});contact.mirrored=true;assert.deepEqual(editor.terminalPosition('SW1:COM'),{x:50,y:125});assert.deepEqual(editor.terminalPosition('SW1:NC'),{x:150,y:125});assert.deepEqual(editor.terminalPosition('SW1:NO'),{x:150,y:100});contact.supplyMirrored=true;assert.deepEqual(editor.terminalPosition('SW1:COM'),{x:50,y:100});editor.schematic.grid.snapGrid={enabled:true,visible:true,stepX:30,stepY:20};contact.position={x:120,y:100};assert.deepEqual(editor.terminalPosition('SW1:NC'),{x:180,y:120});assert.deepEqual(editor.terminalPosition('SW1:NO'),{x:180,y:100});contact.rotation=90;assert.deepEqual(editor.terminalPosition('SW1:COM'),{x:120,y:60});assert.deepEqual(editor.terminalPosition('SW1:NC'),{x:90,y:140});assert.deepEqual(editor.terminalPosition('SW1:NO'),{x:120,y:140})});

test('le miroir des sorties ne retourne pas graphiquement l’arrivée de l’inverseur',()=>{const original=globalThis.document;globalThis.document={createElementNS:(_ns,tag)=>({tag,attributes:{},children:[],setAttribute(name,value){this.attributes[name]=String(value)},append(...nodes){this.children.push(...nodes)}})};try{const renderer=Object.create(SvgRenderer.prototype),contact={id:'SW1',type:'contact',contactType:'CHANGEOVER',commonAlignment:'NC',controlMode:'RE',manualActivated:false,mirrored:true,supplyMirrored:false},schematic={grid:{snapGrid:{stepX:25,stepY:25}}};const nodes=renderer.symbol(contact,{simulation:null},schematic);assert.equal(nodes.length,9);assert.equal(nodes[0].attributes.y1,'0');assert.equal(nodes[6].attributes.y1,'25');assert.equal(nodes[7].attributes.y1,'0');assert.equal(nodes[1].attributes.y1,'36');assert.equal(nodes[1].attributes.y2,'28');assert.equal(nodes[3].attributes.y1,'15');assert.equal(nodes[3].attributes.y2,'35');assert.equal(nodes[4].attributes.y1,'-3');assert.equal(nodes[4].attributes.y2,'-11');contact.mirrored=false;contact.commonAlignment='NO';let state=renderer.symbol(contact,{simulation:null},schematic);assert.equal(state[8].attributes.y2,'25');contact.manualActivated=true;state=renderer.symbol(contact,{simulation:null},schematic);assert.equal(state[8].attributes.y2,'0')}finally{globalThis.document=original}});

test('le titre bleu de la lampe est affiché dans son cercle avant l’identifiant',()=>{const original=globalThis.document;globalThis.document={createElementNS:(_ns,tag)=>({tag,attributes:{},children:[],dataset:{},textContent:'',setAttribute(name,value){this.attributes[name]=String(value)},append(...nodes){this.children.push(...nodes)}})};try{const renderer=Object.create(SvgRenderer.prototype),schematic={grid:{snapGrid:{stepX:25,stepY:25},referenceGrid:{cellWidth:200,cellHeight:150,maxReference:'G12'}}},view={selection:null,selections:new Set(),related:new Set(),simulation:null},lamp={id:'L1',type:'lamp',position:{x:200,y:100},rotation:0,showId:true,showLabel:true,label:'Lampe'};const texts=renderer.componentNode(lamp,schematic,view).children.filter(node=>node.tag==='text'),titles=texts.filter(node=>node.textContent==='Lampe');assert.equal(titles.length,1);assert.match(titles[0].attributes.class,/component-id/);assert.equal(titles[0].attributes.y,'4');assert.equal(texts.find(node=>node.textContent==='L1').attributes.class,'label');assert.equal(texts.find(node=>node.textContent==='L1').attributes.y,'34')}finally{globalThis.document=original}});
test('les textes gardent le même sens de lecture dans les quatre orientations',()=>{const original=globalThis.document;globalThis.document={createElementNS:(_ns,tag)=>({tag,attributes:{},children:[],dataset:{},textContent:'',setAttribute(name,value){this.attributes[name]=String(value)},append(...nodes){this.children.push(...nodes)}})};try{const renderer=Object.create(SvgRenderer.prototype),schematic={grid:{snapGrid:{stepX:25,stepY:25},referenceGrid:{cellWidth:200,cellHeight:150,maxReference:'G12'}}},view={selection:null,selections:new Set(),related:new Set(),simulation:null},lamp={id:'L1',type:'lamp',position:{x:200,y:100},showId:true,showLabel:true,label:'Lampe'};for(const rotation of [0,270]){lamp.rotation=rotation;assert.ok(renderer.componentNode(lamp,schematic,view).children.filter(node=>node.tag==='text').every(node=>!node.attributes.transform))}for(const rotation of [90,180]){lamp.rotation=rotation;assert.ok(renderer.componentNode(lamp,schematic,view).children.filter(node=>node.tag==='text').every(node=>String(node.attributes.transform).startsWith('rotate(180')))}}finally{globalThis.document=original}});

test('un croisement de fils non connectés dessine un pont',()=>{const renderer=Object.create(SvgRenderer.prototype),vertical={id:'WV',from:'A:X',to:'B:X',points:[{x:50,y:0},{x:50,y:100}]},horizontal={id:'WH',from:'C:X',to:'D:X',points:[{x:0,y:50},{x:100,y:50}]},schematic={wires:[vertical,horizontal]};assert.match(renderer.wirePath(vertical,schematic),/ C /);assert.doesNotMatch(renderer.wirePath(horizontal,schematic),/ C /);horizontal.from='A:X';assert.doesNotMatch(renderer.wirePath(vertical,schematic),/ C /)});

test('les nouveaux composants sont orientés de bas vers le haut',()=>{const editor=editorStub();editor.add('lamp',{x:100,y:100});assert.equal(editor.schematic.getComponent('L1').rotation,270);assert.deepEqual(editor.terminalPosition('L1:A'),{x:100,y:150});assert.deepEqual(editor.terminalPosition('L1:B'),{x:100,y:50})});

test('le nouveau contact est un bouton poussoir SW normalement ouvert',()=>{const editor=editorStub();editor.add('contact',{x:100,y:100});const contact=editor.schematic.getComponent('SW1');assert.equal(contact.contactType,'NO');assert.equal(contact.controllerId,null);assert.equal(contact.controlMode,'SW')});

test('les jonctions utilisent la même origine A1 que les lignes horizontales de la grille',()=>{const editor=editorStub();editor.schematic.grid.referenceGrid.cellHeight=153;editor.schematic.grid.referenceGrid.maxReference='G12';editor.schematic.grid.snapGrid.stepX=25;editor.schematic.grid.snapGrid.stepY=25;const point=editor.snap({x:113,y:100});assert.deepEqual(point,{x:125,y:96});editor.add('junction',point);assert.deepEqual(editor.schematic.getComponent('J1').position,{x:125,y:96})});

test('un bouton SW revient au repos au relâchement tandis qu’un contact CT conserve son état',()=>{const editor=editorStub();editor.mode='SIMULATION';editor.pan={x:0,y:0};editor.scale=1;editor.svg={focus(){},getBoundingClientRect:()=>({left:0,top:0})};const sw=editor.schematic.addComponent({id:'SW1',type:'contact',controlMode:'SW'}),ct=editor.schematic.addComponent({id:'CT1',type:'contact',controlMode:'CT'}),event=id=>({button:0,clientX:0,clientY:0,target:{dataset:{},closest:()=>({dataset:{id}})}});editor.down(event('SW1'));assert.equal(sw.manualActivated,true);editor.up();assert.equal(sw.manualActivated,false);editor.down(event('CT1'));editor.up();assert.equal(ct.manualActivated,true);editor.down(event('CT1'));editor.up();assert.equal(ct.manualActivated,false)});

test('le titre reprend l’identifiant et seul le titre est visible par défaut',()=>{const editor=editorStub();editor.add('lamp',{x:100,y:100});const lamp=editor.schematic.getComponent('L1'),wire=editor.schematic.addWire({id:'W1',from:'A:X',to:'B:X',points:[]});assert.equal(lamp.label,'L1');assert.equal(lamp.showId,false);assert.equal(lamp.showLabel,true);assert.equal(wire.showId,false)});
test('une jonction masque son titre et son identifiant par défaut',()=>{const editor=editorStub();editor.add('junction',{x:100,y:100});const junction=editor.schematic.getComponent('J1');assert.equal(junction.label,'J1');assert.equal(junction.showId,false);assert.equal(junction.showLabel,false)});
test('les propriétés affichent toujours l’identifiant puis le titre avec les cases au niveau des champs',()=>{const root={innerHTML:'',querySelectorAll:()=>[]},panel=new PropertyPanel(root,()=>{},()=>{},()=>{}),schematic=new Schematic({components:[{id:'L1',type:'lamp'}]});panel.render(schematic.getComponent('L1'),schematic);assert.ok(root.innerHTML.indexOf('<label>Identifiant</label>')<root.innerHTML.indexOf('<label>Titre</label>'));assert.match(root.innerHTML,/property-value-row/);assert.doesNotMatch(root.innerHTML,/Numéro dans la lampe/)});

test('la barre espace reste disponible dans tous les champs texte',()=>{const editor=editorStub();let prevented=false;editor.key({code:'Space',key:' ',target:{tagName:'INPUT'},preventDefault:()=>{prevented=true}},true);assert.equal(prevented,false);assert.equal(editor.space,undefined);editor.key({code:'Space',key:' ',target:{tagName:'TEXTAREA'},preventDefault:()=>{prevented=true}},true);assert.equal(prevented,false)});

test('le premier Échap annule puis le second active la sélection',()=>{const editor=editorStub();let selectionRequests=0;editor.tool='wire';editor.pendingWire={terminal:'A:X',points:[{x:0,y:0}]};editor.onCancel=()=>selectionRequests++;const event={code:'Escape',key:'Escape',target:{tagName:'BODY'},preventDefault:()=>{}};editor.key(event,true);assert.equal(editor.pendingWire,null);assert.equal(selectionRequests,0);editor.key(event,true);assert.equal(selectionRequests,1)});
