export class CircuitSolver{
 constructor(maxIterations=100){this.maxIterations=maxIterations;}
 solve(schematic,initialCoils=[]){let coils=new Set(initialCoils),state=null;const seen=new Map(),history=[];for(let i=0;i<this.maxIterations;i++){const signature=[...coils].sort().join('|');if(seen.has(signature)){const cycle=history.slice(seen.get(signature)),activated=new Set(cycle.flatMap(set=>[...set]));state=this.pass(schematic,activated);return{...state,activatedCoils:[...activated],converged:false,oscillating:true,iterations:i,diagnostic:'Oscillation détectée : un contact commandé coupe puis rétablit sa propre bobine. État sûr affiché, courant coupé après le contact.'}}seen.set(signature,history.length);history.push(new Set(coils));state=this.pass(schematic,coils);const next=new Set(state.poweredCoils);if(equal(coils,next))return{...state,activatedCoils:[...coils],converged:true,oscillating:false,iterations:i+1,diagnostic:''};coils=next}const safeState=this.pass(schematic,coils);return{...safeState,activatedCoils:[...coils],converged:false,oscillating:true,iterations:this.maxIterations,diagnostic:`Le circuit ne converge pas après ${this.maxIterations} itérations.`};}
 pass(s,coilState){const graph=new Map(),edgeWire=new Map();const add=(a,b,w=null)=>{if(!graph.has(a))graph.set(a,[]);if(!graph.has(b))graph.set(b,[]);graph.get(a).push(b);graph.get(b).push(a);if(w){edgeWire.set(`${a}|${b}`,w);edgeWire.set(`${b}|${a}`,w)}};
  for(const w of s.wires)if(w.from&&w.to)add(w.from,w.to,w.id);
  for(const c of s.components){const a=`${c.id}:A`,b=`${c.id}:B`;if(c.type==='fuse'&&!c.blown)add(a,b);if(c.type==='contact'){const active=c.controllerId?coilState.has(c.controllerId):c.manualActivated;if(c.contactType==='CHANGEOVER')add(`${c.id}:COM`,`${c.id}:${active?'NO':'NC'}`);else{const closed=c.contactType==='NO'?active:!active;if(closed)add(a,b)}} }
  const sources=[],returns=[];for(const p of s.components.filter(c=>c.type==='powerSource')){for(const o of p.outputs.filter(o=>o.enabled))sources.push(`${p.id}:${o.id}`);returns.push(`${p.id}:RETURN`)}
  const primarySources=walk(graph,sources),primaryReturns=walk(graph,returns),poweredTransformers=s.components.filter(c=>c.type==='transformer'&&((primarySources.has(`${c.id}:P1`)&&primaryReturns.has(`${c.id}:P2`))||(primarySources.has(`${c.id}:P2`)&&primaryReturns.has(`${c.id}:P1`))));
  for(const transformer of poweredTransformers){sources.push(`${transformer.id}:S1`,`${transformer.id}:S3`);returns.push(`${transformer.id}:S2`)}
  const fromSource=walk(graph,sources),toReturn=walk(graph,returns);const poweredCoils=s.components.filter(c=>c.type==='coil'&&fromSource.has(`${c.id}:A`)&&toReturn.has(`${c.id}:B`)||c.type==='coil'&&fromSource.has(`${c.id}:B`)&&toReturn.has(`${c.id}:A`)).map(c=>c.id);
  const poweredWires=s.wires.filter(w=>fromSource.has(w.from)||fromSource.has(w.to)||toReturn.has(w.from)||toReturn.has(w.to)).map(w=>w.id);const flowingWires=s.wires.filter(w=>(fromSource.has(w.from)&&toReturn.has(w.to))||(fromSource.has(w.to)&&toReturn.has(w.from))||(fromSource.has(w.from)&&toReturn.has(w.from)&&fromSource.has(w.to))).map(w=>w.id);
  const poweredComponents=s.components.filter(c=>{if(c.type==='transformer')return poweredTransformers.includes(c);if(['coil','lamp','motor'].includes(c.type))return fromSource.has(`${c.id}:A`)&&toReturn.has(`${c.id}:B`)||fromSource.has(`${c.id}:B`)&&toReturn.has(`${c.id}:A`);return c.terminals.some(t=>fromSource.has(`${c.id}:${t.id}`))}).map(c=>c.id);return {poweredCoils,poweredWires,flowingWires,poweredComponents,fromSource,toReturn};}
}
function walk(g,seeds){const seen=new Set(seeds),q=[...seeds];while(q.length){const n=q.shift();for(const v of g.get(n)||[])if(!seen.has(v)){seen.add(v);q.push(v)}}return seen}function equal(a,b){return a.size===b.size&&[...a].every(x=>b.has(x))}
