export class CircuitSolver{
 constructor(maxIterations=100){this.maxIterations=maxIterations;}
 step(schematic,initialCoils=[]){let result=this.solve(schematic,initialCoils),changed=false,active=new Set(result.poweredCoils);for(const counter of schematic.components.filter(component=>component.type==='counter')){const incrementActive=!!counter.incrementRelayId&&active.has(counter.incrementRelayId),resetActive=!!counter.resetRelayId&&active.has(counter.resetRelayId);if(resetActive&&!counter._resetActive){if(counter.currentPosition!==1){counter.currentPosition=1;changed=true}}else if(incrementActive&&!counter._incrementActive){counter.currentPosition=counter.currentPosition%counter.positions+1;changed=true}counter._incrementActive=incrementActive;counter._resetActive=resetActive}if(changed)result=this.solve(schematic,result.poweredCoils);active=new Set(result.poweredCoils);for(const counter of schematic.components.filter(component=>component.type==='counter')){counter._incrementActive=!!counter.incrementRelayId&&active.has(counter.incrementRelayId);counter._resetActive=!!counter.resetRelayId&&active.has(counter.resetRelayId)}let mechanicalChanged=false;const powered=new Set(result.poweredComponents);for(const motor of schematic.components.filter(component=>component.type==='motor')){if(motor.mechanicalPhase==='TRANSITION'){motor.mechanicalStep++;motor.mechanicalPhase='STABLE';mechanicalChanged=true}else if(powered.has(motor.id)){motor.mechanicalPhase='TRANSITION';mechanicalChanged=true}}if(mechanicalChanged)result=this.solve(schematic,result.poweredCoils);return{...result,countersChanged:changed,mechanicalChanged}}
 solve(schematic,initialCoils=[]){const trips=schematic.components.filter(component=>component.type==='coil'&&component.coilKind==='TRIP');let latched=new Set(trips.filter(component=>component._tripLatched).map(component=>component.id)),coils=new Set([...initialCoils,...latched]),state=null;const seen=new Map(),history=[];for(let i=0;i<this.maxIterations;i++){const signature=`${[...coils].sort().join('|')}#${[...latched].sort().join('|')}`;if(seen.has(signature)){const cycle=history.slice(seen.get(signature)),activated=new Set(cycle.flatMap(set=>[...set]));state=this.pass(schematic,activated);commitTrips(trips,latched);return{...state,energizedCoils:state.poweredCoils,activatedCoils:[...activated],poweredComponents:[...new Set([...state.poweredComponents,...latched])],converged:false,oscillating:true,iterations:i,diagnostic:'Oscillation détectée : un contact commandé coupe puis rétablit sa propre bobine. État sûr affiché, courant coupé après le contact.'}}seen.set(signature,history.length);history.push(new Set(coils));state=this.pass(schematic,coils);const energized=new Set(state.poweredCoils),nextLatched=new Set(latched),next=new Set(energized);for(const trip of trips){const released=!!trip.latchRelayId&&energized.has(trip.latchRelayId);if(released){nextLatched.delete(trip.id);next.delete(trip.id)}else if(energized.has(trip.id))nextLatched.add(trip.id);if(nextLatched.has(trip.id))next.add(trip.id)}if(equal(coils,next)&&equal(latched,nextLatched)){commitTrips(trips,nextLatched);return resultWithActiveCoils(state,next,nextLatched,{converged:true,oscillating:false,iterations:i+1,diagnostic:''})}coils=next;latched=nextLatched}const safeState=this.pass(schematic,coils);commitTrips(trips,latched);return resultWithActiveCoils(safeState,coils,latched,{converged:false,oscillating:true,iterations:this.maxIterations,diagnostic:`Le circuit ne converge pas après ${this.maxIterations} itérations.`})}
 pass(s,coilState){const graph=new Map(),edgeWire=new Map(),counterContacts=new Map();for(const counter of s.components.filter(c=>c.type==='counter'))counter.positionContactIds?.forEach((id,index)=>{if(id)counterContacts.set(id,(counterContacts.get(id)||false)||(counter.switchPositions[index]!==false&&counter.currentPosition===index+1))});const add=(a,b,w=null)=>{if(!graph.has(a))graph.set(a,[]);if(!graph.has(b))graph.set(b,[]);graph.get(a).push(b);graph.get(b).push(a);if(w){edgeWire.set(`${a}|${b}`,w);edgeWire.set(`${b}|${a}`,w)}};
  for(const w of s.wires)if(w.from&&w.to)add(w.from,w.to,w.id);
  for(const c of s.components){const a=`${c.id}:A`,b=`${c.id}:B`;if(c.type==='fuse'&&!c.blown)add(a,b);if(c.type==='remoteConnector'&&c.linkedId&&c.id.localeCompare(c.linkedId)<0)add(`${c.id}:J`,`${c.linkedId}:J`);if(c.type==='counter'&&c.switchPositions[c.currentPosition-1]!==false)add(`${c.id}:P${c.currentPosition}A`,`${c.id}:P${c.currentPosition}B`);if(c.type==='adjTip')c.tipPositions.forEach((line,index)=>{if(line)add(`${c.id}:TIP${index+1}`,`${c.id}:LINE${line}`)});if(c.type==='contact'){const active=c.controlMode==='MU'?motorUnitActive(s,c):c.controllerId?coilState.has(c.controllerId):counterContacts.has(c.id)?counterContacts.get(c.id):c.manualActivated;if(c.contactType==='CHANGEOVER'){const rest=c.commonAlignment==='NO'?'NO':'NC',switched=rest==='NO'?'NC':'NO';add(`${c.id}:COM`,`${c.id}:${active?switched:rest}`)}else{const closed=c.contactType==='NO'?active:!active;if(closed)add(a,b)}} }
  const sources=[],returns=[];for(const p of s.components.filter(c=>c.type==='powerSource')){for(const o of p.outputs.filter(o=>o.enabled))sources.push(`${p.id}:${o.id}`);returns.push(`${p.id}:RETURN`)}
  const primarySources=walk(graph,sources),primaryReturns=walk(graph,returns),poweredTransformers=s.components.filter(c=>c.type==='transformer'&&((primarySources.has(`${c.id}:P1`)&&primaryReturns.has(`${c.id}:P2`))||(primarySources.has(`${c.id}:P2`)&&primaryReturns.has(`${c.id}:P1`))));
  for(const transformer of poweredTransformers){sources.push(`${transformer.id}:S1`,`${transformer.id}:S3`);returns.push(`${transformer.id}:S2`)}
  const fromSource=walk(graph,sources),toReturn=walk(graph,returns);const poweredCoils=s.components.filter(c=>c.type==='coil'&&fromSource.has(`${c.id}:A`)&&toReturn.has(`${c.id}:B`)||c.type==='coil'&&fromSource.has(`${c.id}:B`)&&toReturn.has(`${c.id}:A`)).map(c=>c.id);
  const poweredWires=s.wires.filter(w=>fromSource.has(w.from)||fromSource.has(w.to)||toReturn.has(w.from)||toReturn.has(w.to)).map(w=>w.id);const flowingWires=s.wires.filter(w=>(fromSource.has(w.from)&&toReturn.has(w.to))||(fromSource.has(w.to)&&toReturn.has(w.from))||(fromSource.has(w.from)&&toReturn.has(w.from)&&fromSource.has(w.to))).map(w=>w.id);
  const poweredComponents=s.components.filter(c=>{if(c.type==='transformer')return poweredTransformers.includes(c);if(['coil','lamp','motor'].includes(c.type))return fromSource.has(`${c.id}:A`)&&toReturn.has(`${c.id}:B`)||fromSource.has(`${c.id}:B`)&&toReturn.has(`${c.id}:A`);return c.terminals.some(t=>fromSource.has(`${c.id}:${t.id}`))}).map(c=>c.id);return {poweredCoils,poweredWires,flowingWires,poweredComponents,fromSource,toReturn};}
}
function commitTrips(trips,latched){for(const trip of trips)trip._tripLatched=latched.has(trip.id)}
function resultWithActiveCoils(state,active,latched,details){return{...state,energizedCoils:state.poweredCoils,poweredCoils:[...active],activatedCoils:[...active],poweredComponents:[...new Set([...state.poweredComponents,...latched])],...details}}
function walk(g,seeds){const seen=new Set(seeds),q=[...seeds];while(q.length){const n=q.shift();for(const v of g.get(n)||[])if(!seen.has(v)){seen.add(v);q.push(v)}}return seen}function equal(a,b){return a.size===b.size&&[...a].every(x=>b.has(x))}
function mechanicalModulo(value,divisor){return((value%divisor)+divisor)%divisor}
function motorUnitActive(schematic,contact){const unit=schematic.getComponent(contact.motorUnitId),motor=unit&&schematic.getComponent(unit.motorId);if(!unit||motor?.type!=='motor')return false;const position=mechanicalModulo((unit.direction==='CW'?-1:1)*motor.mechanicalStep,unit.movements);return motor.mechanicalPhase==='TRANSITION'?!!unit.transitionStates[position]:!!unit.stableStates[position]}
