import {Component} from './Component.js';
export class PowerSource extends Component{constructor(d={}){super({...d,type:'powerSource',terminals:d.terminals||[{id:'OUT',kind:'output'},{id:'RETURN',kind:'return'}]});this.outputs=d.outputs||[{id:'OUT',label:'24 VAC',voltage:24,enabled:true}];}}
export class Coil extends Component{constructor(d={}){super({...d,type:'coil',terminals:d.terminals||[{id:'A'},{id:'B'}]});this.relayType=d.relayType||'';this.showRelayType=d.showRelayType??true;}}
export class Contact extends Component{constructor(d={}){super({...d,type:'contact',terminals:[{id:'A'},{id:'B'},{id:'COM'},{id:'NC'},{id:'NO'}]});this.contactType=d.contactType||'NO';this.controllerId=d.controllerId||null;this.controlMode=this.controllerId?'RE':d.controlMode==='CT'||String(d.id||'').startsWith('CT')?'CT':'SW';this.manualActivated=!!d.manualActivated;this.mirrored=!!d.mirrored;this.supplyMirrored=!!d.supplyMirrored;this.commonAlignment=d.commonAlignment==='NO'?'NO':'NC';}}
export class Lamp extends Component{constructor(d={}){super({...d,type:'lamp',terminals:d.terminals||[{id:'A'},{id:'B'}]});}}
export class Motor extends Component{constructor(d={}){super({...d,type:'motor',terminals:d.terminals||[{id:'A'},{id:'B'}]});}}
export class Transformer extends Component{constructor(d={}){super({...d,type:'transformer',terminals:[{id:'P1',kind:'primary'},{id:'P2',kind:'primary'},{id:'S1',kind:'phase'},{id:'S2',kind:'neutral'},{id:'S3',kind:'phase'}]});this.heightCells=Math.max(10,d.heightCells||10);}}
export class Fuse extends Component{constructor(d={}){super({...d,type:'fuse',terminals:d.terminals||[{id:'A'},{id:'B'}]});this.rating=d.rating||'10 A';this.blown=!!d.blown;}}
export class Junction extends Component{constructor(d={}){super({...d,label:d.label??d.id,showId:d.showId??false,showLabel:d.showLabel??false,type:'junction',terminals:d.terminals||[{id:'J'}]});}}
export class AdjTip extends Component{constructor(d={}){const rows=Math.max(1,Number(d.rows)||2),multiple=!!d.multipleTips,tipCount=multiple?rows:1,terminals=[...Array.from({length:rows},(_,i)=>({id:`LINE${i+1}`})),...Array.from({length:tipCount},(_,i)=>({id:`TIP${i+1}`}))];super({...d,rotation:d.rotation??0,type:'adjTip',terminals});this.rows=rows;const height=Number(d.heightCells??d.widthCells);this.heightCells=[1,2,3].includes(height)?height:1;this.rowSpacingCells=Number(d.rowSpacingCells)===2?2:1;this.lineLabels=Array.from({length:rows},(_,i)=>String(d.lineLabels?.[i]??i+1));this.multipleTips=multiple;this.tipPositions=Array.from({length:tipCount},(_,i)=>Math.max(0,Math.min(rows,Number(d.tipPositions?.[i])||0)));}}
export class RemoteConnector extends Component{constructor(d={}){super({...d,rotation:d.rotation??0,label:d.label??d.id,showId:d.showId??false,showLabel:d.showLabel??true,type:'remoteConnector',terminals:d.terminals||[{id:'J'}]});this.linkedId=d.linkedId||null;this.direction=d.direction==='out'?'out':'in';this.styleId=d.styleId||'RED';}}
export class Counter extends Component{constructor(d={}){const positions=Math.max(2,Math.min(20,Number(d.positions)||4)),terminals=Array.from({length:positions},(_,i)=>[{id:`P${i+1}A`},{id:`P${i+1}B`}]).flat();super({...d,rotation:d.rotation??0,type:'counter',terminals});this.positions=positions;this.currentPosition=Math.max(1,Math.min(positions,Number(d.currentPosition)||1));this.heightCells=evenCounterHeight(d.heightCells);this.pinSpacingCells=[1,2,3].includes(Number(d.pinSpacingCells))?Number(d.pinSpacingCells):2;this.incrementRelayId=d.incrementRelayId||null;this.resetRelayId=d.resetRelayId||null;this.switchPositions=Array.from({length:positions},(_,i)=>d.switchPositions?.[i]!==false);this.positionContactIds=Array.from({length:positions},(_,i)=>d.positionContactIds?.[i]||null);Object.defineProperty(this,'_incrementActive',{value:false,writable:true,enumerable:false});Object.defineProperty(this,'_resetActive',{value:false,writable:true,enumerable:false});}}
const evenCounterHeight=value=>Math.max(4,Math.min(12,Math.round((Number(value)||4)/2)*2));
const componentClasses={powerSource:PowerSource,coil:Coil,contact:Contact,lamp:Lamp,motor:Motor,transformer:Transformer,fuse:Fuse,junction:Junction,adjTip:AdjTip,remoteConnector:RemoteConnector,counter:Counter};
export const componentFromData=d=>{const Type=componentClasses[d.type]||Component;return Type===Component?new Component(d):new Type(d)};
