import {Component} from './Component.js';
export class PowerSource extends Component{constructor(d={}){super({...d,type:'powerSource',terminals:d.terminals||[{id:'OUT',kind:'output'},{id:'RETURN',kind:'return'}]});this.outputs=d.outputs||[{id:'OUT',label:'24 VAC',voltage:24,enabled:true}];}}
export class Coil extends Component{constructor(d={}){super({...d,type:'coil',terminals:d.terminals||[{id:'A'},{id:'B'}]});this.relayType=d.relayType||'';}}
export class Contact extends Component{constructor(d={}){super({...d,type:'contact',terminals:[{id:'A'},{id:'B'},{id:'COM'},{id:'NC'},{id:'NO'}]});this.contactType=d.contactType||'NO';this.controllerId=d.controllerId||null;this.controlMode=this.controllerId?'RE':d.controlMode==='CT'||String(d.id||'').startsWith('CT')?'CT':'SW';this.manualActivated=!!d.manualActivated;this.mirrored=!!d.mirrored;this.commonAlignment=d.commonAlignment==='NO'?'NO':'NC';}}
export class Lamp extends Component{constructor(d={}){super({...d,type:'lamp',terminals:d.terminals||[{id:'A'},{id:'B'}]});this.number=d.number||'';}}
export class Motor extends Component{constructor(d={}){super({...d,type:'motor',terminals:d.terminals||[{id:'A'},{id:'B'}]});}}
export class Transformer extends Component{constructor(d={}){super({...d,type:'transformer',terminals:[{id:'P1',kind:'primary'},{id:'P2',kind:'primary'},{id:'S1',kind:'phase'},{id:'S2',kind:'neutral'},{id:'S3',kind:'phase'}]});this.heightCells=Math.max(10,d.heightCells||10);}}
export class Fuse extends Component{constructor(d={}){super({...d,type:'fuse',terminals:d.terminals||[{id:'A'},{id:'B'}]});this.rating=d.rating||'10 A';this.blown=!!d.blown;}}
export class Junction extends Component{constructor(d={}){super({...d,label:d.label??'',type:'junction',terminals:d.terminals||[{id:'J'}]});}}
export class AdjTip extends Component{constructor(d={}){const rows=Math.max(1,Number(d.rows)||2),multiple=!!d.multipleTips,tipCount=multiple?rows:1,terminals=[...Array.from({length:rows},(_,i)=>({id:`LINE${i+1}`})),...Array.from({length:tipCount},(_,i)=>({id:`TIP${i+1}`}))];super({...d,type:'adjTip',terminals});this.rows=rows;this.heightCells=Number(d.heightCells)===2?2:3;this.lineLabels=Array.from({length:rows},(_,i)=>String(d.lineLabels?.[i]??i+1));this.multipleTips=multiple;this.tipPositions=Array.from({length:tipCount},(_,i)=>Math.max(0,Math.min(rows,Number(d.tipPositions?.[i])||0)));}}
export const componentFromData=d=>({powerSource:PowerSource,coil:Coil,contact:Contact,lamp:Lamp,motor:Motor,transformer:Transformer,fuse:Fuse,junction:Junction,adjTip:AdjTip}[d.type]||Component)===Component?new Component(d):new ({powerSource:PowerSource,coil:Coil,contact:Contact,lamp:Lamp,motor:Motor,transformer:Transformer,fuse:Fuse,junction:Junction,adjTip:AdjTip}[d.type])(d);
