import {componentFromData} from './components.js';import {Wire,WireStyle} from './Wire.js';
export class Schematic{
 constructor(data={}){this.formatVersion=1;this.name=data.name||'Nouveau projet';this.brand=data.brand||'';this.year=data.year||null;this.background=data.background||null;this.grid=data.grid||{snapGrid:{enabled:true,stepX:25,stepY:25,visible:true},referenceGrid:{enabled:true,visible:true,cellWidth:200,cellHeight:150,calculatedCellWidth:200,calculatedCellHeight:150,maxReference:'G12'}};this.grid.referenceGrid.maxReference||='G12';this.grid.referenceGrid.calculatedCellWidth??=this.grid.referenceGrid.cellWidth;this.grid.referenceGrid.calculatedCellHeight??=this.grid.referenceGrid.cellHeight;this.components=(data.components||[]).map(componentFromData);this.wires=(data.wires||[]).map(w=>new Wire(w));const supplied=data.wireStyles||[],missing=defaultStyles().filter(style=>!supplied.some(existing=>existing.id===style.id));this.wireStyles=[...missing,...supplied].map(s=>new WireStyle(s));this.relations=data.relations||[];}
 getComponent(id){return this.components.find(c=>c.id===id)} getWire(id){return this.wires.find(w=>w.id===id)}
 addComponent(c){this.components.push(componentFromData(c));return this.components.at(-1)} addWire(w){this.wires.push(new Wire(w));return this.wires.at(-1)}
 remove(id){this.components=this.components.filter(c=>c.id!==id);this.wires=this.wires.filter(w=>w.id!==id&&!w.from?.startsWith(id+':')&&!w.to?.startsWith(id+':'));this.components.filter(c=>c.controllerId===id).forEach(c=>c.controllerId=null);}
 renameComponent(oldId,newId){newId=String(newId).trim();if(!newId)throw new Error('L’identifiant est obligatoire');if(newId!==oldId&&[...this.components,...this.wires].some(item=>item.id===newId))throw new Error(`L’identifiant « ${newId} » est déjà utilisé`);const component=this.getComponent(oldId);if(!component)return null;const rename=reference=>reference?.startsWith(`${oldId}:`)?`${newId}${reference.slice(oldId.length)}`:reference;for(const wire of this.wires){wire.from=rename(wire.from);wire.to=rename(wire.to)}for(const contact of this.components)if(contact.controllerId===oldId)contact.controllerId=newId;component.id=newId;return component;}
 renameWire(oldId,newId){newId=String(newId).trim();if(!newId)throw new Error('L’identifiant est obligatoire');if(newId!==oldId&&[...this.components,...this.wires].some(item=>item.id===newId))throw new Error(`L’identifiant « ${newId} » est déjà utilisé`);const wire=this.getWire(oldId);if(wire)wire.id=newId;return wire;}
 nextId(prefix){let n=1;const ids=new Set([...this.components,...this.wires].map(x=>x.id));while(ids.has(`${prefix}${n}`))n++;return `${prefix}${n}`;}
 toJSON(){return {formatVersion:this.formatVersion,name:this.name,brand:this.brand,year:this.year,background:this.background,grid:this.grid,wireStyles:this.wireStyles,components:this.components,wires:this.wires,relations:this.components.filter(c=>c.type==='contact'&&c.controllerId).map(c=>({type:'coilControlsContact',from:c.controllerId,to:c.id}))};}
}
export const defaultStyles=()=>[{id:'RED',name:'Rouge',colors:['#e52337']},{id:'BLUE',name:'Bleu',colors:['#257ce5']},{id:'YELLOW',name:'Jaune',colors:['#ffd21f']},{id:'GREEN',name:'Vert',colors:['#12ad55']},{id:'WHITE',name:'Blanc',colors:['#ffffff']},{id:'BROWN',name:'Marron',colors:['#6f4529']},{id:'ORANGE',name:'Orange',colors:['#ff8a1f']},{id:'BLACK',name:'Noir',colors:['#111111']},{id:'GRAY',name:'Gris',colors:['#7d8793']},{id:'VIOLET',name:'Violet',colors:['#6840d8']}];
export function parseReference(value='G12'){const match=String(value).trim().toUpperCase().match(/^([A-Z]+)-?(\d+)$/);if(!match)return null;let rows=0;for(const letter of match[1])rows=rows*26+letter.charCodeAt(0)-64;const columns=Number(match[2]);return rows>0&&columns>0?{rows,columns,label:`${match[1]}${columns}`}:null}
export function gridExtent(grid){const maximum=parseReference(grid.maxReference)||parseReference('G12');return{width:maximum.columns*grid.cellWidth,height:maximum.rows*grid.cellHeight,...maximum}}
export function referenceOf(position,grid,height=gridExtent(grid).height){const col=Math.max(1,Math.floor(position.x/grid.cellWidth)+1);const row=Math.max(0,Math.floor((height-position.y)/grid.cellHeight));return `${letters(row)}-${col}`;}function letters(n){let s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s;}
