import {Schematic} from '../model/Schematic.js';

const PROJECT_PICKER_ID='ipcs-projects-v2';
const PROJECT_FILE_TYPES=[{description:'Projet IPCSX',accept:{'application/octet-stream':['.ipcsx']}},{description:'Ancien projet IPCS',accept:{'application/json':['.ipcs','.json']}}];
const encoder=new TextEncoder(),decoder=new TextDecoder();

export class SchematicSerializer{
 static stringify(s){return JSON.stringify(s.toV2JSON(),null,2)}
 static parse(text){const data=JSON.parse(text);if(![1,2].includes(data.formatVersion))throw new Error(`Version IPCS non supportée : ${data.formatVersion}`);return new Schematic(data)}
 static fileName(s){return `${slug(s.name)||'projet'}.ipcsx`}
 static legacyFileName(s){return `${slug(s.name)||'projet'}.ipcs`}
 static pack(s){const data=s.toV2JSON(),background=data.background?{...data.background}:null,entries=[];if(background?.dataUrl){const comma=background.dataUrl.indexOf(','),header=background.dataUrl.slice(0,comma),bytes=base64ToBytes(background.dataUrl.slice(comma+1));background.resource='background.bin';background.encoding='binary';background.mimeType=background.mimeType||header.match(/^data:([^;,]+)/)?.[1]||'application/pdf';delete background.dataUrl;entries.push({name:'background.bin',data:bytes})}data.background=background;entries.unshift({name:'project.json',data:encoder.encode(JSON.stringify(data))});return createZip(entries)}
 static unpack(buffer){const bytes=new Uint8Array(buffer),entries=readZip(bytes),project=entries.get('project.json');if(!project)throw new Error('Le conteneur IPCSX ne contient pas project.json');const data=JSON.parse(decoder.decode(project));if(data.formatVersion!==2)throw new Error(`Version IPCSX non supportée : ${data.formatVersion}`);if(data.background?.resource){const asset=entries.get(data.background.resource);if(!asset)throw new Error(`Ressource absente : ${data.background.resource}`);data.background.dataUrl=`data:${data.background.mimeType||'application/octet-stream'};base64,${bytesToBase64(asset)}`;delete data.background.resource;delete data.background.encoding}return new Schematic(data)}
 static async parseFile(file){if(!file.arrayBuffer)return this.parse(await file.text());const bytes=new Uint8Array(await file.arrayBuffer());return bytes[0]===0x50&&bytes[1]===0x4b?this.unpack(bytes.buffer):this.parse(decoder.decode(bytes))}
 static async save(s,existingHandle=null){const contents=this.pack(s);if('showSaveFilePicker'in window){let handle=existingHandle;if(!handle||!handle.name?.toLowerCase().endsWith('.ipcsx'))handle=await window.showSaveFilePicker({id:PROJECT_PICKER_ID,startIn:'documents',suggestedName:this.fileName(s),types:[PROJECT_FILE_TYPES[0]]});const writable=await handle.createWritable();await writable.write(contents);await writable.close();return handle}this.download(s);return null}
 static async open(){if('showOpenFilePicker'in window){const [handle]=await window.showOpenFilePicker({id:PROJECT_PICKER_ID,startIn:'documents',multiple:false,types:PROJECT_FILE_TYPES});const file=await handle.getFile(),name=String(file.name||handle.name||'');return {schematic:await this.parseFile(file),handle:name.toLowerCase().endsWith('.ipcsx')?handle:null,legacy:name.toLowerCase().endsWith('.ipcs')}}return null}
 static download(s){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([this.pack(s)],{type:'application/octet-stream'}));a.href=url;a.download=this.fileName(s);a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
}

function createZip(entries){let offset=0;const locals=[],centrals=[];for(const entry of entries){const name=encoder.encode(entry.name),data=entry.data instanceof Uint8Array?entry.data:new Uint8Array(entry.data),crc=crc32(data),local=new Uint8Array(30+name.length+data.length),view=new DataView(local.buffer);view.setUint32(0,0x04034b50,true);view.setUint16(4,20,true);view.setUint32(14,crc,true);view.setUint32(18,data.length,true);view.setUint32(22,data.length,true);view.setUint16(26,name.length,true);local.set(name,30);local.set(data,30+name.length);locals.push(local);const central=new Uint8Array(46+name.length),centralView=new DataView(central.buffer);centralView.setUint32(0,0x02014b50,true);centralView.setUint16(4,20,true);centralView.setUint16(6,20,true);centralView.setUint32(16,crc,true);centralView.setUint32(20,data.length,true);centralView.setUint32(24,data.length,true);centralView.setUint16(28,name.length,true);centralView.setUint32(42,offset,true);central.set(name,46);centrals.push(central);offset+=local.length}const centralSize=centrals.reduce((sum,item)=>sum+item.length,0),end=new Uint8Array(22),endView=new DataView(end.buffer);endView.setUint32(0,0x06054b50,true);endView.setUint16(8,entries.length,true);endView.setUint16(10,entries.length,true);endView.setUint32(12,centralSize,true);endView.setUint32(16,offset,true);return concat([...locals,...centrals,end])}
function readZip(bytes){const entries=new Map();let offset=0;while(offset+30<=bytes.length){const view=new DataView(bytes.buffer,bytes.byteOffset+offset);if(view.getUint32(0,true)!==0x04034b50)break;const method=view.getUint16(8,true),size=view.getUint32(18,true),nameLength=view.getUint16(26,true),extraLength=view.getUint16(28,true);if(method!==0)throw new Error('Compression IPCSX non supportée');const name=decoder.decode(bytes.subarray(offset+30,offset+30+nameLength)),start=offset+30+nameLength+extraLength;entries.set(name,bytes.slice(start,start+size));offset=start+size}return entries}
function concat(parts){const result=new Uint8Array(parts.reduce((sum,item)=>sum+item.length,0));let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length}return result}
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return(crc^0xffffffff)>>>0}
function base64ToBytes(value){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}
function bytesToBase64(bytes){let result='',chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)result+=String.fromCharCode(...bytes.subarray(i,i+chunk));return btoa(result)}
function slug(value){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()}
