import {gridExtent,referenceOf} from '../model/Schematic.js';
const NS='http://www.w3.org/2000/svg';const el=(tag,a={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);return n};
export class SvgRenderer{
 constructor(svg){this.svg=svg;this.layers={grid:svg.querySelector('#gridLayer'),wire:svg.querySelector('#wireLayer'),component:svg.querySelector('#componentLayer'),overlay:svg.querySelector('#overlayLayer')};this.defs=svg.querySelector('#svgDefs');}
 render(s,view={selection:null,selections:new Set(),related:new Set(),simulation:null,wirePreview:null,marquee:null}){this.renderDefs(s);this.renderGrid(s);this.layers.wire.replaceChildren(...s.wires.flatMap(w=>this.wireNodes(w,s,view)));this.layers.component.replaceChildren(...s.components.map(c=>this.componentNode(c,s,view)));this.layers.overlay.replaceChildren(...this.overlayNodes(s,view));}
 renderDefs(s){this.defs.replaceChildren();for(const st of s.wireStyles){const p=el('pattern',{id:`style-${safe(st.id)}`,patternUnits:'userSpaceOnUse',width:12,height:12,patternTransform:'rotate(45)'});st.colors.forEach((c,i)=>p.append(el('rect',{x:i*12/st.colors.length,y:0,width:12/st.colors.length+1,height:12,fill:c})));this.defs.append(p)}}
 renderGrid(s){const g=this.layers.grid;g.replaceChildren();const snap=s.grid.snapGrid,ref=s.grid.referenceGrid,{width:W,height:H}=gridExtent(ref);if(snap.visible){for(let x=0;x<=W;x+=snap.stepX)g.append(el('line',{x1:x,y1:0,x2:x,y2:H,class:'snap-grid'}));for(let y=H;y>=0;y-=snap.stepY)g.append(el('line',{x1:0,y1:y,x2:W,y2:y,class:'snap-grid'}))}if(ref.visible){for(let x=0;x<=W+.001;x+=ref.cellWidth)g.append(el('line',{x1:x,y1:0,x2:x,y2:H,class:'reference-grid'}));for(let y=H;y>=-.001;y-=ref.cellHeight)g.append(el('line',{x1:0,y1:y,x2:W,y2:y,class:'reference-grid'}));for(let x=ref.cellWidth/2,n=1;x<W;x+=ref.cellWidth,n++){for(const y of [22,H-10]){const t=el('text',{x,y,class:'grid-label'});t.textContent=n;g.append(t)}}for(let y=H-ref.cellHeight/2,n=0;y>0;y-=ref.cellHeight,n++){for(const x of [18,W-18]){const t=el('text',{x,y:y+5,class:'grid-label'});t.textContent=gridLetters(n);g.append(t)}}}}
 wireNodes(w,s,v){const d=`M ${w.points.map(p=>`${p.x} ${p.y}`).join(' L ')}`,st=s.wireStyles.find(x=>x.id===w.styleId)||s.wireStyles[0],powered=v.simulation?.poweredWires.includes(w.id),selected=v.selection===w.id||v.selections?.has(w.id);const group=el('g',{'data-id':w.id,class:`wire ${selected?'selected':''}`});if(w.description){const title=el('title');title.textContent=w.description;group.append(title)}if(powered)group.append(el('path',{d,class:'wire-glow'}));if(selected)group.append(el('path',{d,class:'wire-glow',style:'stroke:#168bc1;opacity:.45'}));group.append(el('path',{d,class:'wire-base',stroke:`url(#style-${safe(st.id)})`}),el('path',{d,class:'wire-hit'}));return [group]}
 componentNode(c,s,v){const classes=['component',v.selection===c.id||v.selections?.has(c.id)?'selected':'',v.related.has(c.id)?'related':'',v.simulation?.poweredComponents.includes(c.id)?'powered':''].join(' '),transformer=c.type==='transformer',half=transformer?c.heightCells/2*s.grid.snapGrid.stepY:0,side=transformer?2*s.grid.snapGrid.stepX:0;const g=el('g',{class:classes,'data-id':c.id,transform:`translate(${c.position.x} ${c.position.y}) rotate(${c.rotation})`});g.append(el('rect',{x:transformer?-side-10:-60,y:transformer?-half-10:-44,width:transformer?side*2+20:120,height:transformer?half*2+35:c.type==='coil'?104:88,rx:5,class:'selection-box'}));this.symbol(c,v,s).forEach(n=>g.append(n));const id=el('text',{x:0,y:transformer?-half-12:-31,class:'component-id'});id.textContent=c.id;const label=el('text',{x:0,y:transformer?half+20:46,class:'label'});label.textContent=c.type==='coil'?'':c.label;g.append(id,label);if(c.type==='coil'&&c.relayType){const type=el('text',{x:0,y:46,class:'label'});type.textContent=c.relayType;g.append(type)}if(c.type==='powerSource')g.append(this.terminal(-50,0,c,'OUT'),this.terminal(50,0,c,'RETURN'));else if(c.type==='junction')g.append(this.terminal(0,0,c,'J'));else if(transformer)g.append(this.terminal(-side,-half,c,'P1'),this.terminal(-side,half,c,'P2'),this.terminal(side,-half,c,'S1'),this.terminal(side,0,c,'S2'),this.terminal(side,half,c,'S3'));else if(c.type==='contact'&&c.contactType==='CHANGEOVER'){const mirror=c.mirrored?-1:1;g.append(this.terminal(-50,0,c,'COM'),this.terminal(50,-14*mirror,c,'NC'),this.terminal(50,14*mirror,c,'NO'))}else g.append(this.terminal(-50,0,c,'A'),this.terminal(50,0,c,'B'));g.dataset.reference=referenceOf(c.position,s.grid.referenceGrid);return g}
 terminal(x,y,c,id){return el('circle',{cx:x,cy:y,r:6,class:'terminal','data-terminal':`${c.id}:${id}`})}
 symbol(c,v,s){
  if(c.type==='powerSource'){const q=el('circle',{cx:0,cy:0,r:20,class:'symbol-line'}),t=el('text',{x:0,y:7,class:'label',style:'font-size:22px'});t.textContent='~';return [el('line',{x1:-50,y1:0,x2:-20,y2:0,class:'symbol-line'}),q,t,el('line',{x1:20,y1:0,x2:50,y2:0,class:'symbol-line'})]}
  if(c.type==='coil')return [el('line',{x1:-50,y1:0,x2:-28,y2:0,class:'symbol-line'}),el('path',{d:'M-28 0 C-26 -15 -16 -15 -14 0 C-12 -15 -2 -15 0 0 C2 -15 12 -15 14 0 C16 -15 26 -15 28 0',class:'symbol-line'}),el('line',{x1:28,y1:0,x2:50,y2:0,class:'symbol-line'})];
  if(c.type==='lamp'){const number=el('text',{x:0,y:7,class:'label',style:'font-size:18px;font-weight:bold'});number.textContent=c.number;return[el('line',{x1:-50,y1:0,x2:-20,y2:0,class:'symbol-line'}),el('circle',{cx:0,cy:0,r:20,class:'symbol-line'}),number,el('line',{x1:20,y1:0,x2:50,y2:0,class:'symbol-line'})]}
  if(c.type==='motor')return[el('line',{x1:-50,y1:0,x2:-28,y2:0,class:'symbol-line'}),el('line',{x1:-34,y1:10,x2:-24,y2:-7,class:'symbol-line'}),el('circle',{cx:0,cy:0,r:22,class:'symbol-line'}),el('line',{x1:24,y1:7,x2:34,y2:-10,class:'symbol-line'}),el('line',{x1:28,y1:0,x2:50,y2:0,class:'symbol-line'})];
  if(c.type==='transformer'){const half=c.heightCells/2*s.grid.snapGrid.stepY,side=2*s.grid.snapGrid.stepX,coil=.7*s.grid.snapGrid.stepX;return[el('line',{x1:-side,y1:-half,x2:-coil,y2:-half,class:'symbol-line'}),el('line',{x1:-side,y1:half,x2:-coil,y2:half,class:'symbol-line'}),el('path',{d:windingPath(-coil,half,-.65*s.grid.snapGrid.stepX),class:'symbol-line'}),el('line',{x1:-.2*s.grid.snapGrid.stepX,y1:-half,x2:-.2*s.grid.snapGrid.stepX,y2:half,class:'symbol-line'}),el('line',{x1:.2*s.grid.snapGrid.stepX,y1:-half,x2:.2*s.grid.snapGrid.stepX,y2:half,class:'symbol-line'}),el('path',{d:windingPath(coil,half,.65*s.grid.snapGrid.stepX),class:'symbol-line'}),el('line',{x1:coil,y1:-half,x2:side,y2:-half,class:'symbol-line'}),el('line',{x1:coil,y1:0,x2:side,y2:0,class:'symbol-line'}),el('line',{x1:coil,y1:half,x2:side,y2:half,class:'symbol-line'})]}
  if(c.type==='fuse'){const rating=el('text',{x:0,y:-17,class:'label'});rating.textContent=c.rating;return[el('line',{x1:-50,y1:0,x2:-24,y2:0,class:'symbol-line'}),el('circle',{cx:-21,cy:0,r:3,class:'symbol-line'}),el('path',{d:'M-18 0 C-12 -16 -4 -16 0 0 C4 16 12 16 18 0',class:'symbol-line'}),el('circle',{cx:21,cy:0,r:3,class:'symbol-line'}),el('line',{x1:24,y1:0,x2:50,y2:0,class:'symbol-line'}),rating]}
  if(c.type==='contact'){const active=c.controlType==='manual'?c.manualActivated:(v.simulation?.activatedCoils||v.simulation?.poweredCoils||[]).includes(c.controllerId);if(c.contactType==='CHANGEOVER'){const nodes=[el('line',{x1:-50,y1:0,x2:-22,y2:0,class:'symbol-line'}),el('line',{x1:-22,y1:0,x2:-9,y2:-14,class:'symbol-line'}),el('line',{x1:-22,y1:0,x2:-9,y2:14,class:'symbol-line'}),el('line',{x1:-8,y1:-25,x2:-8,y2:-3,class:'symbol-line'}),el('line',{x1:8,y1:-25,x2:8,y2:-3,class:'symbol-line'}),el('line',{x1:-13,y1:-4,x2:13,y2:-24,class:'symbol-line'}),el('line',{x1:-8,y1:3,x2:-8,y2:25,class:'symbol-line'}),el('line',{x1:8,y1:3,x2:8,y2:25,class:'symbol-line'}),el('line',{x1:8,y1:-14,x2:50,y2:-14,class:'symbol-line'}),el('line',{x1:8,y1:14,x2:50,y2:14,class:'symbol-line'}),el('line',{x1:-22,y1:0,x2:8,y2:active?14:-14,class:'symbol-line',style:'stroke:#168bc1;stroke-width:5'})];if(!c.mirrored)return nodes;const mirrored=el('g',{transform:'scale(1 -1)','data-mirrored':'true'});mirrored.append(...nodes);return[mirrored]}const closed=c.contactType==='NO'?active:!active,nodes=[el('line',{x1:-50,y1:0,x2:-7,y2:0,class:'symbol-line'}),el('line',{x1:-7,y1:-13,x2:-7,y2:13,class:'symbol-line'}),el('line',{x1:7,y1:-13,x2:7,y2:13,class:'symbol-line'}),el('line',{x1:7,y1:0,x2:50,y2:0,class:'symbol-line'})];if(c.contactType==='NC')nodes.push(el('line',{x1:-13,y1:14,x2:13,y2:-14,class:'symbol-line'}));if(closed)nodes.push(el('line',{x1:-7,y1:0,x2:7,y2:0,class:'symbol-line',style:'stroke:#168bc1;stroke-width:5'}));return nodes}
  return [el('circle',{cx:0,cy:0,r:7,class:'junction-dot'})]
 }
 overlayNodes(s,v){const out=[];if(v.marquee){const r=v.marquee;out.push(el('rect',{x:r.x,y:r.y,width:r.width,height:r.height,class:'marquee-selection'}))}if(v.selection){const c=s.getComponent(v.selection);if(c&&(c.type==='coil'||c.type==='contact'&&c.controllerId)){const coil=c.type==='coil'?c:s.getComponent(c.controllerId);for(const ct of s.components.filter(x=>x.type==='contact'&&x.controllerId===coil?.id))out.push(el('line',{x1:coil.position.x,y1:coil.position.y,x2:ct.position.x,y2:ct.position.y,class:'relation-line'}))}const wire=s.getWire(v.selection);if(wire)for(let i=1;i<wire.points.length-1;i++)out.push(el('circle',{cx:wire.points[i].x,cy:wire.points[i].y,r:7,class:`wire-point-handle ${v.selectedWirePoint===i?'active':''}`,'data-wire-point':i,'data-wire-id':wire.id}))}if(v.wirePreview?.length)out.push(el('polyline',{points:v.wirePreview.map(p=>`${p.x},${p.y}`).join(' '),class:'symbol-line',style:'stroke:#168bc1;stroke-dasharray:6 4'}));return out}
}
function gridLetters(n){let s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s}function safe(s){return String(s).replace(/[^a-z0-9_-]/gi,'-')}function windingPath(x,half,bulge){let d=`M ${x} ${-half}`,segments=10;for(let i=0;i<segments;i++){const middle=-half+(i+.5)*half*2/segments,end=-half+(i+1)*half*2/segments;d+=` Q ${x+bulge} ${middle} ${x} ${end}`}return d}
