import {referenceOf} from '../model/Schematic.js';
const NS='http://www.w3.org/2000/svg';const el=(tag,a={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(a))n.setAttribute(k,v);return n};
export class SvgRenderer{
 constructor(svg){this.svg=svg;this.layers={grid:svg.querySelector('#gridLayer'),wire:svg.querySelector('#wireLayer'),component:svg.querySelector('#componentLayer'),overlay:svg.querySelector('#overlayLayer')};this.defs=svg.querySelector('#svgDefs');}
 render(s,view={selection:null,selections:new Set(),related:new Set(),simulation:null,wirePreview:null,marquee:null}){this.renderDefs(s);this.renderGrid(s);this.layers.wire.replaceChildren(...s.wires.flatMap(w=>this.wireNodes(w,s,view)));this.layers.component.replaceChildren(...s.components.map(c=>this.componentNode(c,s,view)));this.layers.overlay.replaceChildren(...this.overlayNodes(s,view));}
 renderDefs(s){this.defs.replaceChildren();for(const st of s.wireStyles){const p=el('pattern',{id:`style-${safe(st.id)}`,patternUnits:'userSpaceOnUse',width:12,height:12,patternTransform:'rotate(45)'});st.colors.forEach((c,i)=>p.append(el('rect',{x:i*12/st.colors.length,y:0,width:12/st.colors.length+1,height:12,fill:c})));this.defs.append(p)}}
 renderGrid(s){const g=this.layers.grid;g.replaceChildren();const snap=s.grid.snapGrid,ref=s.grid.referenceGrid,W=3000,H=1800;if(snap.visible){for(let x=0;x<=W;x+=snap.stepX)g.append(el('line',{x1:x,y1:0,x2:x,y2:H,class:'snap-grid'}));for(let y=0;y<=H;y+=snap.stepY)g.append(el('line',{x1:0,y1:y,x2:W,y2:y,class:'snap-grid'}))}if(ref.visible){for(let x=0;x<=W;x+=ref.cellWidth)g.append(el('line',{x1:x,y1:0,x2:x,y2:H,class:'reference-grid'}));for(let y=0;y<=H;y+=ref.cellHeight)g.append(el('line',{x1:0,y1:y,x2:W,y2:y,class:'reference-grid'}));for(let x=ref.cellWidth/2,n=1;x<W;x+=ref.cellWidth,n++){const t=el('text',{x,y:22,class:'grid-label'});t.textContent=n;g.append(t)}for(let y=H-ref.cellHeight/2,n=0;y>0;y-=ref.cellHeight,n++){const t=el('text',{x:18,y:y+5,class:'grid-label'});t.textContent=gridLetters(n);g.append(t)}}}
 wireNodes(w,s,v){const d=`M ${w.points.map(p=>`${p.x} ${p.y}`).join(' L ')}`,st=s.wireStyles.find(x=>x.id===w.styleId)||s.wireStyles[0],powered=v.simulation?.poweredWires.includes(w.id),selected=v.selection===w.id||v.selections?.has(w.id);const group=el('g',{'data-id':w.id,class:`wire ${selected?'selected':''}`});if(powered)group.append(el('path',{d,class:'wire-glow'}));if(selected)group.append(el('path',{d,class:'wire-glow',style:'stroke:#168bc1;opacity:.45'}));group.append(el('path',{d,class:'wire-base',stroke:`url(#style-${safe(st.id)})`}),el('path',{d,class:'wire-hit'}));return [group]}
 componentNode(c,s,v){const classes=['component',v.selection===c.id||v.selections?.has(c.id)?'selected':'',v.related.has(c.id)?'related':'',v.simulation?.poweredComponents.includes(c.id)?'powered':''].join(' ');const g=el('g',{class:classes,'data-id':c.id,transform:`translate(${c.position.x} ${c.position.y}) rotate(${c.rotation})`});g.append(el('rect',{x:-55,y:-32,width:110,height:64,rx:5,class:'selection-box'}));const symbol=this.symbol(c,v);symbol.forEach(n=>g.append(n));const id=el('text',{x:0,y:-19,class:'component-id'});id.textContent=c.id;const label=el('text',{x:0,y:42,class:'label'});label.textContent=c.label;g.append(id,label);if(c.type==='powerSource')g.append(this.terminal(-50,0,c,'OUT'),this.terminal(50,0,c,'RETURN'));else if(c.type!=='junction')g.append(this.terminal(-50,0,c,'A'),this.terminal(50,0,c,'B'));else g.append(this.terminal(0,0,c,'J'));g.dataset.reference=referenceOf(c.position,s.grid.referenceGrid,1800);return g}
 terminal(x,y,c,id){return el('circle',{cx:x,cy:y,r:6,class:'terminal','data-terminal':`${c.id}:${id}`})}
 symbol(c,v){if(c.type==='powerSource'){const q=el('circle',{cx:0,cy:0,r:20,class:'symbol-line'}),t=el('text',{x:0,y:7,class:'label',style:'font-size:22px'});t.textContent='~';return [el('line',{x1:-50,y1:0,x2:-20,y2:0,class:'symbol-line'}),q,t,el('line',{x1:20,y1:0,x2:50,y2:0,class:'symbol-line'})]}if(c.type==='coil'){return [el('line',{x1:-50,y1:0,x2:-28,y2:0,class:'symbol-line'}),el('rect',{x:-28,y:-14,width:56,height:28,rx:14,class:'symbol-line coil-fill',fill:'#fff'}),el('path',{d:'M-19 8 Q-12 -8 -5 8 T9 8 T23 8',class:'symbol-line',style:'stroke-width:2'}),el('line',{x1:28,y1:0,x2:50,y2:0,class:'symbol-line'})]}if(c.type==='contact'){const active=c.controlType==='manual'?c.manualActivated:v.simulation?.poweredCoils.includes(c.controllerId),closed=c.contactType==='NO'?active:!active;return [el('line',{x1:-50,y1:0,x2:-18,y2:0,class:'symbol-line'}),el('circle',{cx:-16,cy:0,r:3,class:'symbol-line'}),el('circle',{cx:16,cy:0,r:3,class:'symbol-line'}),el('line',{x1:18,y1:0,x2:50,y2:0,class:'symbol-line'}),el('line',{x1:-13,y1:closed?0:-2,x2:13,y2:closed?0:-14,class:'symbol-line'})]}return [el('circle',{cx:0,cy:0,r:7,class:'junction-dot'})]}
 overlayNodes(s,v){const out=[];if(v.marquee){const r=v.marquee;out.push(el('rect',{x:r.x,y:r.y,width:r.width,height:r.height,class:'marquee-selection'}))}if(v.selection){const c=s.getComponent(v.selection);if(c&&(c.type==='coil'||c.type==='contact'&&c.controllerId)){const coil=c.type==='coil'?c:s.getComponent(c.controllerId);for(const ct of s.components.filter(x=>x.type==='contact'&&x.controllerId===coil?.id))out.push(el('line',{x1:coil.position.x,y1:coil.position.y,x2:ct.position.x,y2:ct.position.y,class:'relation-line'}))}const wire=s.getWire(v.selection);if(wire)for(let i=1;i<wire.points.length-1;i++)out.push(el('circle',{cx:wire.points[i].x,cy:wire.points[i].y,r:7,class:`wire-point-handle ${v.selectedWirePoint===i?'active':''}`,'data-wire-point':i,'data-wire-id':wire.id}))}if(v.wirePreview?.length)out.push(el('polyline',{points:v.wirePreview.map(p=>`${p.x},${p.y}`).join(' '),class:'symbol-line',style:'stroke:#168bc1;stroke-dasharray:6 4'}));return out}
}
function gridLetters(n){let s='';do{s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)-1}while(n>=0);return s}function safe(s){return String(s).replace(/[^a-z0-9_-]/gi,'-')}
