import {defaultStyles,gridExtent,parseReference,Schematic} from './model/Schematic.js';
import {createExample} from './model/example.js';
import {SvgRenderer} from './rendering/SvgRenderer.js';
import {Editor} from './editor/Editor.js';
import {CircuitSolver} from './simulation/CircuitSolver.js';
import {SchematicSerializer} from './persistence/SchematicSerializer.js';
import {ComponentPalette} from './ui/ComponentPalette.js';
import {PropertyPanel} from './ui/PropertyPanel.js';
import {WireStyle} from './model/Wire.js';

let schematic=createExample(),simulation=null,fileHandle=null,dirty=false,pendingNewBackground=null;
let pdfImageToken=0,pdfCalibration=null;const pdfImageCache=new Map();
const $=selector=>document.querySelector(selector);
const svg=$('#schematic'),renderer=new SvgRenderer(svg),solver=new CircuitSolver();
if(window.pdfjsLib)window.pdfjsLib.GlobalWorkerOptions.workerSrc='vendor/pdfjs/pdf.worker.min.js';
const toast=message=>{const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2400)};

const editor=new Editor({svg,schematic,renderer,
 onViewportChange:syncPdfViewport,
 onCancel:()=>palette.select('select'),
 onChange:(reason,replacement)=>{if(replacement){schematic=replacement;editor.schematic=schematic}markDirty();editor.mode==='SIMULATION'?runSimulation():refresh()},
 onSelect:(id,ids=[])=>{const item=ids.length===1?(schematic.getComponent(id)||schematic.getWire(id)):null;properties.render(item,schematic);$('#statusSelection').textContent=ids.length>1?`${ids.length} éléments sélectionnés`:item?`${item.id}${item.type?' · '+item.type:''}`:'Aucune sélection'},
 onStatus:(point,message)=>{if(point)$('#statusPosition').textContent=`x ${Math.round(point.x)} · y ${Math.round(point.y)}`;if(message)$('#statusMessage').textContent=message}
});
const palette=new ComponentPalette($('#palette'),tool=>{editor.tool=tool==='select'?null:tool;$('#canvasEmpty').classList.toggle('hidden',tool!=='select');editor.pendingWire=null;editor.preview=null;editor.render();renderStyles()});
function renameContactForMode(contact){const prefix=contact.controlMode==='RE'?'RE-CT':contact.controlMode==='CT'?'CT':'SW';if(contact.id.startsWith(prefix)||!/^(?:SW|CT|RE-CT)\d+$/.test(contact.id))return;const newId=schematic.nextId(prefix);schematic.renameComponent(contact.id,newId);editor.selection=newId;editor.selections=new Set([newId])}
const properties=new PropertyPanel($('#properties'),(property,value)=>{const item=schematic.getComponent(editor.selection)||schematic.getWire(editor.selection);if(!item)return;if(property==='id'){const oldId=item.id,newId=String(value).trim(),existing=schematic.getComponent(newId)||schematic.getWire(newId);if(!newId||newId!==oldId&&existing){toast(!newId?'L’identifiant est obligatoire':`L’identifiant « ${newId} » est déjà utilisé`);refresh();return}if(newId===oldId)return;editor.snapshot();item.type?schematic.renameComponent(oldId,newId):schematic.renameWire(oldId,newId);editor.selection=newId;editor.selections=new Set([newId]);markDirty();refresh();return}editor.snapshot();if(property==='contactType'&&item.type==='contact'&&item.contactType!==value){const oldChangeover=item.contactType==='CHANGEOVER',newChangeover=value==='CHANGEOVER',map=reference=>{if(!reference?.startsWith(`${item.id}:`)||oldChangeover===newChangeover)return reference;const terminal=reference.slice(reference.lastIndexOf(':')+1);if(newChangeover)return `${item.id}:${terminal==='A'?'COM':item.contactType==='NC'?'NC':'NO'}`;return `${item.id}:${terminal==='COM'?'A':'B'}`};for(const wire of schematic.wires){wire.from=map(wire.from);wire.to=map(wire.to)}}if(property==='controlMode'&&item.type==='contact'){if(value==='RE'){const firstRelay=schematic.components.filter(component=>component.type==='coil').sort((a,b)=>a.id.localeCompare(b.id,'fr',{numeric:true}))[0];if(!firstRelay){toast('Ajoutez d’abord un relais à associer');refresh();return}item.controllerId=firstRelay.id}else item.controllerId=null;item.controlMode=value;item.manualActivated=false;renameContactForMode(item)}else if(property==='controllerId'&&item.type==='contact'){item.controllerId=value||null;item.controlMode=item.controllerId?'RE':item.controlMode;renameContactForMode(item)}else{if(property==='tipPosition'&&item.type==='adjTip'){const used=item.tipPositions.findIndex((line,index)=>index!==value.index&&line===value.line);if(value.line&&used>=0)item.tipPositions[used]=0;item.tipPositions[value.index]=value.line}else if(property==='rows'&&item.type==='adjTip'){item.rows=Math.max(1,Math.min(20,Number(value)||1));item.tipPositions=item.tipPositions.map(line=>line<=item.rows?line:0);if(item.multipleTips){while(item.tipPositions.length<item.rows)item.tipPositions.push(0);item.tipPositions.length=item.rows}}else if(property==='multipleTips'&&item.type==='adjTip'){item.multipleTips=value;item.tipPositions=value?Array.from({length:item.rows},(_,i)=>item.tipPositions[i]||0):[item.tipPositions[0]||0]}else if(property==='heightCells')value=Math.max(10,Number(value)||10);if(property==='x'||property==='y')item.position[property]=value;else item[property]=value}if(item.type&&['x','y','rotation','contactType','heightCells','mirrored','commonAlignment'].includes(property))editor.syncConnectedWires(item);markDirty();refresh()},()=>editor.remove(),updateProjectProperty);
function projectCaption(){return [schematic.brand,schematic.year].filter(Boolean).length?`${schematic.name} · ${[schematic.brand,schematic.year].filter(Boolean).join(' ')}`:schematic.name}
function markDirty(value=true){dirty=value;document.title=`${value?'• ':''}${schematic.name} — IPCS`;$('#projectTitle').textContent=`${projectCaption()}${value?' — non sauvegardé':''}`}
function refresh(){editor.render(simulation);renderStyles();renderBackground();const item=schematic.getComponent(editor.selection)||schematic.getWire(editor.selection);properties.render(item,schematic)}
function syncPdfViewport(){}
function renderBackground(){const image=$('#pdfBackground'),bg=schematic.background,active=bg?.visible&&bg?.dataUrl,height=gridExtent(schematic.grid.referenceGrid).height;if(active){image.setAttribute('x',bg.x??0);image.setAttribute('y',height-(bg.y??0)-(bg.height??900));image.setAttribute('width',bg.width??1200);image.setAttribute('height',bg.height??900);image.setAttribute('opacity',(bg.opacity??50)/100);image.removeAttribute('hidden');setPdfImage(bg.dataUrl,image)}else{image.setAttribute('hidden','');image.removeAttribute('href')}$('#canvasWrap').classList.toggle('has-background',!!active)}
function pdfBytes(dataUrl){const base64=dataUrl.slice(dataUrl.indexOf(',')+1),binary=atob(base64),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes}
async function pdfSize(dataUrl){if(!window.pdfjsLib)throw new Error('La bibliothèque PDF.js est indisponible');const document=await window.pdfjsLib.getDocument({data:pdfBytes(dataUrl)}).promise,page=await document.getPage(1),viewport=page.getViewport({scale:1});return{width:Math.round(viewport.width),height:Math.round(viewport.height)}}
async function pdfToImage(dataUrl){if(pdfImageCache.has(dataUrl))return pdfImageCache.get(dataUrl);const promise=(async()=>{if(!window.pdfjsLib)throw new Error('La bibliothèque PDF.js est indisponible');const pdfDocument=await window.pdfjsLib.getDocument({data:pdfBytes(dataUrl)}).promise,page=await pdfDocument.getPage(1),native=page.getViewport({scale:1}),scale=Math.max(.25,Math.min(6,6000/Math.max(native.width,native.height),Math.sqrt(32000000/(native.width*native.height)))),viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d',{alpha:false}),viewport}).promise;const blob=await new Promise((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Conversion du PDF impossible')),'image/png'));return URL.createObjectURL(blob)})();pdfImageCache.set(dataUrl,promise);try{return await promise}catch(error){pdfImageCache.delete(dataUrl);throw error}}
async function setPdfImage(dataUrl,image){const token=++pdfImageToken;try{const url=await pdfToImage(dataUrl);if(token===pdfImageToken&&schematic.background?.dataUrl===dataUrl)image.setAttribute('href',url)}catch(error){if(token===pdfImageToken)toast(`Affichage du PDF impossible : ${error.message}`)}}
function runSimulation(){const previousCoils=simulation?.poweredCoils||simulation?.activatedCoils||[];simulation=solver.solve(schematic,previousCoils);editor.render(simulation);$('#statusMessage').textContent=simulation.converged?`${simulation.poweredCoils.length} bobine(s) alimentée(s) · ${simulation.iterations} passe(s)`:simulation.diagnostic}
function sortedWireStyles(){return [...schematic.wireStyles].sort((a,b)=>a.colors.length-b.colors.length||a.name.localeCompare(b.name,'fr',{sensitivity:'base'}))}
function renderStyles(){const root=$('#wireStyles');root.replaceChildren(...sortedWireStyles().map(style=>{const row=document.createElement('div'),button=document.createElement('button'),edit=document.createElement('button');row.className='wire-style-row';button.className=`wire-style ${editor.styleId===style.id&&editor.tool==='wire'?'active':''}`;button.innerHTML=`<span class="wire-swatch" style="background:linear-gradient(135deg,${style.colors.map((color,index)=>`${color} ${index/style.colors.length*100}%,${color} ${(index+1)/style.colors.length*100}%`).join(',')})"></span><span>${style.name}</span>`;button.onclick=()=>{editor.styleId=style.id;editor.tool='wire';editor.pendingWire=null;editor.preview=null;palette.deselect();$('#canvasEmpty').classList.add('hidden');editor.render();renderStyles()};edit.type='button';edit.className='wire-style-edit';edit.textContent='✎';edit.title=`Modifier le style ${style.name}`;edit.onclick=()=>openWireStyleDialog(style);row.append(button,edit);return row}))}
function setMode(mode){editor.setMode(mode);simulation=mode==='SIMULATION'?solver.solve(schematic):null;$('#editMode').classList.toggle('active',mode==='EDIT');$('#simMode').classList.toggle('active',mode==='SIMULATION');$('#statusMode').textContent=mode==='EDIT'?'ÉDITION':'SIMULATION';palette.clear();editor.tool=null;mode==='SIMULATION'?runSimulation():refresh()}
function loadProject(project,handle=null){schematic=project;fileHandle=handle;simulation=null;editor.setSchematic(schematic);setMode('EDIT');markDirty(false);refresh();toast(`Projet « ${schematic.name} » ouvert`)}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
function numberValue(selector,fallback){const value=Number($(selector).value);return Number.isFinite(value)?value:fallback}
const parseMaxReference=parseReference;
function calibrationPoint(event){const canvas=$('#pdfCalibrationCanvas'),rect=canvas.getBoundingClientRect(),size=pdfCalibration.size;return{x:(event.clientX-rect.left)/rect.width*size.width,y:size.height-(event.clientY-rect.top)/rect.height*size.height}}
function positionCalibrationMarker(marker,point){const canvas=$('#pdfCalibrationCanvas'),x=canvas.offsetLeft+point.x/pdfCalibration.size.width*canvas.clientWidth,y=canvas.offsetTop+(1-point.y/pdfCalibration.size.height)*canvas.clientHeight;marker.style.left=`${x}px`;marker.style.top=`${y}px`;marker.hidden=false}
function resetCalibrationPoints(){if(!pdfCalibration)return;pdfCalibration.origin=null;pdfCalibration.limit=null;$('#pdfAnchorA1').hidden=true;$('#pdfAnchorMax').hidden=true;$('#confirmPdfCalibration').disabled=true;$('#pdfCalibrationStatus').textContent='Cliquez sur le point A1 du PDF.'}
async function renderCalibrationPreview(){const state=pdfCalibration;if(!state)return;if(state.renderTask){state.renderTask.cancel();try{await state.renderTask.promise}catch{}}const density=Math.max(1,window.devicePixelRatio||1),displayScale=state.fitScale*state.zoom,renderScale=Math.min(8,displayScale*density),viewport=state.page.getViewport({scale:renderScale}),canvas=$('#pdfCalibrationCanvas'),context=canvas.getContext('2d',{alpha:false});canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.style.width=`${Math.round(state.size.width*displayScale)}px`;canvas.style.height=`${Math.round(state.size.height*displayScale)}px`;$('#pdfCalibrationStage').classList.toggle('zoomed',state.zoom>1);$('#pdfCalibrationZoomReset').textContent=`${Math.round(state.zoom*100)} %`;state.renderTask=state.page.render({canvasContext:context,viewport});try{await state.renderTask.promise}catch(error){if(error?.name!=='RenderingCancelledException')throw error}if(pdfCalibration!==state)return;state.renderTask=null;if(state.origin)positionCalibrationMarker($('#pdfAnchorA1'),state.origin);if(state.limit)positionCalibrationMarker($('#pdfAnchorMax'),state.limit)}
async function openPdfCalibration(file,defaultReference='F27'){const dataUrl=await fileToDataUrl(file),document=await window.pdfjsLib.getDocument({data:pdfBytes(dataUrl)}).promise,page=await document.getPage(1),native=page.getViewport({scale:1}),size={width:native.width,height:native.height},availableWidth=Math.min(900,window.innerWidth-80),availableHeight=Math.max(280,window.innerHeight-350),fitScale=Math.min(1,availableWidth/size.width,availableHeight/size.height);$('#pdfMaxReference').value=defaultReference||'F27';pdfCalibration={file,dataUrl,size,page,fitScale,zoom:1,origin:null,limit:null};resetCalibrationPoints();await renderCalibrationPreview();$('#pdfCalibrationStage').scrollTo(0,0);$('#pdfCalibrationDialog').showModal();return new Promise(resolve=>pdfCalibration.resolve=resolve)}
function closePdfCalibration(result=null){const state=pdfCalibration;if(!state)return;pdfCalibration=null;$('#pdfCalibrationDialog').close();state.resolve(result)}
$('#pdfCalibrationCanvas').onclick=event=>{if(!pdfCalibration)return;const point=calibrationPoint(event);if(!pdfCalibration.origin){pdfCalibration.origin=point;positionCalibrationMarker($('#pdfAnchorA1'),point);$('#pdfCalibrationStatus').textContent='Cliquez maintenant sur le repère maximal en haut à droite.';return}if(!pdfCalibration.limit){if(point.x<=pdfCalibration.origin.x||point.y<=pdfCalibration.origin.y){toast('Le second point doit être au-dessus et à droite de A1');return}pdfCalibration.limit=point;positionCalibrationMarker($('#pdfAnchorMax'),point);$('#pdfAnchorMax').textContent=parseMaxReference($('#pdfMaxReference').value)?.label||'MAX';$('#pdfCalibrationStatus').textContent='Les deux points sont définis. Vous pouvez importer le PDF.';$('#confirmPdfCalibration').disabled=!parseMaxReference($('#pdfMaxReference').value);return}resetCalibrationPoints()};
$('#pdfMaxReference').oninput=()=>{const max=parseMaxReference($('#pdfMaxReference').value);$('#pdfAnchorMax').textContent=max?.label||'MAX';$('#confirmPdfCalibration').disabled=!(max&&pdfCalibration?.origin&&pdfCalibration?.limit)};
$('#pdfCalibrationForm').onsubmit=event=>{event.preventDefault();const state=pdfCalibration,max=parseMaxReference($('#pdfMaxReference').value);if(!state?.origin||!state.limit||!max)return;const width=state.limit.x-state.origin.x,height=state.limit.y-state.origin.y,background={name:state.file.name,mimeType:state.file.type||'application/pdf',dataUrl:state.dataUrl,visible:true,opacity:50,x:-state.origin.x,y:-state.origin.y,width:state.size.width,height:state.size.height,originalWidth:state.size.width,originalHeight:state.size.height};closePdfCalibration({background,maxReference:max.label,cellWidth:width/max.columns,cellHeight:height/max.rows})};
$('#closePdfCalibration').onclick=$('#cancelPdfCalibration').onclick=()=>closePdfCalibration();
$('#pdfCalibrationDialog').oncancel=event=>{event.preventDefault();closePdfCalibration()};
async function changeCalibrationZoom(factor){if(!pdfCalibration)return;const stage=$('#pdfCalibrationStage'),oldZoom=pdfCalibration.zoom,centerX=(stage.scrollLeft+stage.clientWidth/2)/Math.max(1,stage.scrollWidth),centerY=(stage.scrollTop+stage.clientHeight/2)/Math.max(1,stage.scrollHeight);pdfCalibration.zoom=factor===0?1:Math.min(8,Math.max(.5,oldZoom*factor));await renderCalibrationPreview();stage.scrollLeft=centerX*stage.scrollWidth-stage.clientWidth/2;stage.scrollTop=centerY*stage.scrollHeight-stage.clientHeight/2}
$('#pdfCalibrationZoomOut').onclick=()=>changeCalibrationZoom(.75);$('#pdfCalibrationZoomReset').onclick=()=>changeCalibrationZoom(0);$('#pdfCalibrationZoomIn').onclick=()=>changeCalibrationZoom(1.5);
$('#pdfCalibrationStage').onwheel=event=>{if(!event.ctrlKey)return;event.preventDefault();changeCalibrationZoom(event.deltaY<0?1.25:.8)};
async function updateProjectProperty(path,value){try{const [section,key]=path.split('.');if(path==='background.file'){const result=await openPdfCalibration(value,schematic.grid.referenceGrid.maxReference||'F27');if(!result)return;schematic.background=result.background;Object.assign(schematic.grid.referenceGrid,{maxReference:result.maxReference,cellWidth:result.cellWidth,cellHeight:result.cellHeight,calculatedCellWidth:result.cellWidth,calculatedCellHeight:result.cellHeight})}else if(path==='background.remove')schematic.background=null;else if(path==='referenceGrid.resetCalculated'){const ref=schematic.grid.referenceGrid;ref.cellWidth=ref.calculatedCellWidth;ref.cellHeight=ref.calculatedCellHeight}else if(section==='background'){if(!schematic.background)return;if(key==='width'||key==='height'){const ratio=(schematic.background.originalWidth||schematic.background.width)/(schematic.background.originalHeight||schematic.background.height);schematic.background[key]=value;if(key==='width')schematic.background.height=value/ratio;else schematic.background.width=value*ratio}else schematic.background[key]=value}else if(key)schematic.grid[section][key]=value;else schematic[section]=value;if(path==='background.file'||path.startsWith('referenceGrid.'))editor.resetView();markDirty();editor.render(simulation);renderBackground();if(path.startsWith('background.')||path==='referenceGrid.resetCalculated')properties.render(null,schematic)}catch(error){toast(`Modification du projet impossible : ${error.message}`)}}

async function saveProject(){try{fileHandle=await SchematicSerializer.save(schematic,fileHandle);markDirty(false);toast(fileHandle?'Projet sauvegardé dans le fichier local':'Projet téléchargé dans votre dossier Téléchargements')}catch(error){if(error.name!=='AbortError')toast(`Échec de la sauvegarde : ${error.message}`)}}
async function openProject(){try{const result=await SchematicSerializer.open();if(result)loadProject(result.schematic,result.handle);else $('#fileInput').click()}catch(error){if(error.name!=='AbortError')toast(`Impossible d’ouvrir ce projet : ${error.message}`)}}
function fillDialog(project){const bg=project?.background;pendingNewBackground=null;$('#projectName').value=project?.name||'Nouveau projet';$('#projectBrand').value=project?.brand||'';$('#projectYear').value=project?.year||'';$('#backgroundPdfInput').value='';$('#pdfFileName').textContent=bg?.name||'Aucun fichier sélectionné'}
function openProjectDialog(){$('#projectDialogTitle').textContent='Nouveau projet';$('#projectDialogHelp').textContent='Créez un espace de travail vide. Un plan PDF peut être placé en arrière-plan pour servir de guide.';$('#projectSubmitBtn').textContent='Créer le projet';fillDialog(null);$('#newProjectDialog').showModal();setTimeout(()=>$('#projectName').select())}

$('#newProjectForm').onsubmit=async event=>{event.preventDefault();const name=$('#projectName').value.trim();if(!name)return;const data={name,brand:$('#projectBrand').value.trim(),year:$('#projectYear').value?numberValue('#projectYear',null):null,background:pendingNewBackground?.background||null,grid:pendingNewBackground?{snapGrid:{enabled:true,stepX:25,stepY:25,visible:true},referenceGrid:{enabled:true,visible:true,cellWidth:pendingNewBackground.cellWidth,cellHeight:pendingNewBackground.cellHeight,calculatedCellWidth:pendingNewBackground.cellWidth,calculatedCellHeight:pendingNewBackground.cellHeight,maxReference:pendingNewBackground.maxReference}}:undefined};$('#newProjectDialog').close();loadProject(new Schematic(data));fileHandle=null;markDirty(true);toast(`Projet « ${name} » créé`)};
$('#backgroundPdfInput').onchange=async event=>{const file=event.target.files[0];if(!file){pendingNewBackground=null;$('#pdfFileName').textContent='Aucun fichier sélectionné';return}try{const result=await openPdfCalibration(file,'F27');if(result){pendingNewBackground=result;$('#pdfFileName').textContent=`${file.name} · calibré jusqu’à ${result.maxReference}`}else{event.target.value='';pendingNewBackground=null;$('#pdfFileName').textContent='Aucun fichier sélectionné'}}catch(error){event.target.value='';pendingNewBackground=null;$('#pdfFileName').textContent='Aucun fichier sélectionné';toast(`Lecture du PDF impossible : ${error.message}`)}};
$('#newBtn').onclick=openProjectDialog;$('#projectSettingsBtn').onclick=()=>{palette.select('select');editor.select(null);properties.render(null,schematic);$('#statusMessage').textContent='Propriétés du projet'};$('#closeNewDialog').onclick=()=>$('#newProjectDialog').close();$('#cancelNewProject').onclick=()=>$('#newProjectDialog').close();
$('#saveBtn').onclick=saveProject;$('#openBtn').onclick=openProject;
$('#fileInput').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{loadProject(SchematicSerializer.parse(await file.text()))}catch(error){toast(`Fichier IPCS invalide : ${error.message}`)}finally{event.target.value=''}};
$('#editMode').onclick=()=>setMode('EDIT');$('#simMode').onclick=()=>setMode('SIMULATION');$('#undoBtn').onclick=()=>editor.undo();$('#redoBtn').onclick=()=>editor.redo();$('#zoomIn').onclick=()=>editor.zoom(1.2);$('#zoomOut').onclick=()=>editor.zoom(.8);$('#zoomReset').onclick=()=>editor.zoom(0);
const wirePalette=[['#ffffff','Blanc'],['#f2e8d5','Ivoire'],['#f7c6c7','Rose pâle'],['#ef6b73','Corail'],['#e52337','Rouge'],['#a90d23','Rouge foncé'],['#6d071a','Bordeaux'],['#2b050b','Grenat'],['#ffd6a0','Abricot'],['#ff9f43','Orange'],['#f06b22','Orange foncé'],['#bd3518','Rouille'],['#ffe68a','Jaune pâle'],['#ffd21f','Jaune'],['#d9a514','Ocre'],['#806515','Moutarde'],['#c9f17b','Vert clair'],['#65d83b','Vert'],['#12ad55','Émeraude'],['#087044','Vert foncé'],['#b8f1e8','Turquoise pâle'],['#43d8cf','Turquoise'],['#119d9a','Sarcelle'],['#075b62','Bleu-vert'],['#b8e3fa','Bleu ciel'],['#48b9ef','Cyan'],['#257ce5','Bleu'],['#1645a5','Bleu foncé'],['#c8c5ff','Lavande'],['#8c78f0','Violet clair'],['#6840d8','Violet'],['#41208d','Violet foncé'],['#efb3ef','Mauve pâle'],['#df58d8','Magenta'],['#b31ab8','Pourpre'],['#720774','Prune'],['#ffc1d0','Rose'],['#ff5b8e','Rose vif'],['#dc1f62','Framboise'],['#890d42','Rose foncé'],['#d9dde2','Gris clair'],['#9ba3ad','Gris'],['#626b78','Gris foncé'],['#303640','Anthracite'],['#c49a72','Beige'],['#8a6042','Brun'],['#523520','Marron'],['#111111','Noir']];let selectedWireColors=[];
const primaryWireStyles=defaultStyles(),primaryWireColors=primaryWireStyles.map(style=>style.colors[0]);for(const style of primaryWireStyles)if(!wirePalette.some(([color])=>color===style.colors[0]))wirePalette.push([style.colors[0],style.name]);wirePalette.sort((a,b)=>{const rank=color=>{const index=primaryWireColors.indexOf(color);return index<0?1000:index};return rank(a[0])-rank(b[0])});let editingWireStyleId=null,suggestedWireStyleName='';
function wireStyleNameFromColors(colors){return colors.map(color=>schematic.wireStyles.find(style=>style.colors.length===1&&style.colors[0].toLowerCase()===color.toLowerCase())?.name||wirePalette.find(([value])=>value.toLowerCase()===color.toLowerCase())?.[1]||color).join('-')}
function renderWireColorDialog(){const palette=$('#wireColorPalette');palette.replaceChildren(...wirePalette.map(([color,name])=>{const button=document.createElement('button');button.type='button';button.className='wire-color';button.title=name;button.style.background=color;button.classList.toggle('active',selectedWireColors.includes(color));button.onclick=()=>{const index=selectedWireColors.indexOf(color);if(index>=0)selectedWireColors.splice(index,1);else if(selectedWireColors.length<3)selectedWireColors.push(color);else{toast('Un style peut contenir au maximum trois couleurs');return}if(!editingWireStyleId){const input=$('#wireStyleName');if(!input.value.trim()||input.value===suggestedWireStyleName){suggestedWireStyleName=wireStyleNameFromColors(selectedWireColors);input.value=suggestedWireStyleName}}renderWireColorDialog()};return button}));const selection=$('#wireColorSelection');selection.replaceChildren(...selectedWireColors.map(color=>{const swatch=document.createElement('span');swatch.style.background=color;return swatch}));selection.dataset.empty=selectedWireColors.length?'': 'Choisissez de 1 à 3 couleurs';$('#confirmWireStyle').disabled=!selectedWireColors.length}
function closeWireStyleDialog(){$('#wireStyleDialog').close();editingWireStyleId=null}
function openWireStyleDialog(style=null){editingWireStyleId=style?.id||null;selectedWireColors=style?[...style.colors]:[];suggestedWireStyleName='';$('#wireStyleName').value=style?.name||'';$('#wireStyleDialogTitle').textContent=style?'Modifier le style de fil':'Nouveau style de fil';$('#confirmWireStyle').textContent=style?'Enregistrer':'Créer le style';renderWireColorDialog();$('#wireStyleDialog').showModal()}
$('#addStyleBtn').onclick=()=>openWireStyleDialog();$('#closeWireStyleDialog').onclick=$('#cancelWireStyle').onclick=closeWireStyleDialog;$('#wireStyleDialog').oncancel=event=>{event.preventDefault();closeWireStyleDialog()};$('#wireStyleForm').onsubmit=event=>{event.preventDefault();if(!selectedWireColors.length)return;const existing=schematic.wireStyles.find(style=>style.id===editingWireStyleId),name=$('#wireStyleName').value.trim()||wireStyleNameFromColors(selectedWireColors),others=schematic.wireStyles.filter(style=>style!==existing),colorKey=selectedWireColors.map(color=>color.toLowerCase()).join('|');if(others.some(style=>style.name.localeCompare(name,'fr',{sensitivity:'base'})===0)){toast(`Le nom de style « ${name} » existe déjà`);$('#wireStyleName').focus();return}if(others.some(style=>style.colors.map(color=>color.toLowerCase()).join('|')===colorKey)){toast('Un style utilisant ces couleurs dans le même ordre existe déjà');return}if(existing){existing.name=name;existing.colors=[...selectedWireColors];editor.styleId=existing.id}else{const style=new WireStyle({id:`STYLE-${Date.now()}`,name,colors:[...selectedWireColors]});schematic.wireStyles.push(style);editor.styleId=style.id}closeWireStyleDialog();markDirty();refresh()};
window.addEventListener('keydown',event=>{if(event.ctrlKey&&event.key.toLowerCase()==='s'){event.preventDefault();saveProject()}if(event.ctrlKey&&event.key.toLowerCase()==='o'){event.preventDefault();openProject()}if(event.ctrlKey&&event.key.toLowerCase()==='n'){event.preventDefault();openProjectDialog()}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
markDirty(false);refresh();
