import {Schematic} from './model/Schematic.js';import {createExample} from './model/example.js';import {SvgRenderer} from './rendering/SvgRenderer.js';import {Editor} from './editor/Editor.js';import {CircuitSolver} from './simulation/CircuitSolver.js';import {SchematicSerializer} from './persistence/SchematicSerializer.js';import {ComponentPalette} from './ui/ComponentPalette.js';import {PropertyPanel} from './ui/PropertyPanel.js';import {WireStyle} from './model/Wire.js';
let schematic=createExample(),simulation=null;const $=s=>document.querySelector(s),svg=$('#schematic'),renderer=new SvgRenderer(svg),solver=new CircuitSolver();
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2200)};
const editor=new Editor({svg,schematic,renderer,onChange:(reason,replacement)=>{if(replacement){schematic=replacement;editor.schematic=schematic}if(editor.mode==='SIMULATION')runSimulation();else refresh();},onSelect:id=>{const item=schematic.getComponent(id)||schematic.getWire(id);properties.render(item,schematic);$('#statusSelection').textContent=item?`${item.id}${item.type?' · '+item.type:''}`:'Aucune sélection'},onStatus:(p,msg)=>{if(p)$('#statusPosition').textContent=`x ${Math.round(p.x)} · y ${Math.round(p.y)}`;if(msg)$('#statusMessage').textContent=msg}});
const palette=new ComponentPalette($('#palette'),tool=>{editor.tool=tool;$('#canvasEmpty').classList.toggle('hidden',!!tool);if(tool!=='wire'){editor.pendingWire=null;editor.preview=null}editor.render()});
const properties=new PropertyPanel($('#properties'),(prop,value)=>{const item=schematic.getComponent(editor.selection)||schematic.getWire(editor.selection);if(!item)return;editor.snapshot();if(prop==='x'||prop==='y')item.position[prop]=value;else item[prop]=value;refresh();properties.render(item,schematic)},()=>editor.remove());
function refresh(){editor.render(simulation);renderStyles();const item=schematic.getComponent(editor.selection)||schematic.getWire(editor.selection);properties.render(item,schematic)}
function runSimulation(){simulation=solver.solve(schematic);editor.render(simulation);$('#statusMessage').textContent=simulation.converged?`${simulation.poweredCoils.length} bobine(s) alimentée(s) · ${simulation.iterations} passe(s)`:simulation.diagnostic}
function renderStyles(){const root=$('#wireStyles');root.replaceChildren(...schematic.wireStyles.map(st=>{const b=document.createElement('button');b.className=`wire-style ${editor.styleId===st.id?'active':''}`;b.innerHTML=`<span class="wire-swatch" style="background:linear-gradient(135deg,${st.colors.map((c,i)=>`${c} ${i/st.colors.length*100}%,${c} ${(i+1)/st.colors.length*100}%`).join(',')})"></span><span>${st.name}</span>`;b.onclick=()=>{editor.styleId=st.id;renderStyles()};return b}))}
function mode(m){editor.setMode(m);simulation=m==='SIMULATION'?solver.solve(schematic):null;$('#editMode').classList.toggle('active',m==='EDIT');$('#simMode').classList.toggle('active',m==='SIMULATION');$('#statusMode').textContent=m==='EDIT'?'ÉDITION':'SIMULATION';palette.clear();editor.tool=null;if(m==='SIMULATION')runSimulation();else refresh()}
$('#editMode').onclick=()=>mode('EDIT');$('#simMode').onclick=()=>mode('SIMULATION');$('#saveBtn').onclick=()=>{SchematicSerializer.download(schematic);toast('Schéma exporté')};$('#openBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=async e=>{try{schematic=SchematicSerializer.parse(await e.target.files[0].text());editor.setSchematic(schematic);simulation=null;refresh();toast('Schéma importé')}catch(err){toast(err.message)}e.target.value=''};
$('#newBtn').onclick=()=>{schematic=new Schematic();editor.setSchematic(schematic);simulation=null;refresh();toast('Nouveau schéma')};$('#undoBtn').onclick=()=>editor.undo();$('#redoBtn').onclick=()=>editor.redo();$('#zoomIn').onclick=()=>editor.zoom(1.2);$('#zoomOut').onclick=()=>editor.zoom(.8);$('#zoomReset').onclick=()=>editor.zoom(0);
$('#addStyleBtn').onclick=()=>{const colors=prompt('Couleurs CSS séparées par des virgules (1 à 3)','#2d7bd8,#ffffff');if(!colors)return;const list=colors.split(',').map(x=>x.trim()).filter(Boolean).slice(0,3);const id=`STYLE-${Date.now()}`;schematic.wireStyles.push(new WireStyle({id,name:list.join(' / '),colors:list}));editor.styleId=id;refresh()};
window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();SchematicSerializer.download(schematic)}if(e.ctrlKey&&e.key.toLowerCase()==='n'){e.preventDefault();$('#newBtn').click()}});refresh();
