import {Schematic} from './model/Schematic.js';
import {createExample} from './model/example.js';
import {SvgRenderer} from './rendering/SvgRenderer.js';
import {Editor} from './editor/Editor.js';
import {CircuitSolver} from './simulation/CircuitSolver.js';
import {SchematicSerializer} from './persistence/SchematicSerializer.js';
import {ComponentPalette} from './ui/ComponentPalette.js';
import {PropertyPanel} from './ui/PropertyPanel.js';
import {WireStyle} from './model/Wire.js';

let schematic=createExample(),simulation=null,fileHandle=null,dirty=false,dialogMode='new',removeBackground=false;
const $=selector=>document.querySelector(selector);
const svg=$('#schematic'),renderer=new SvgRenderer(svg),solver=new CircuitSolver();
const toast=message=>{const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2400)};

const editor=new Editor({svg,schematic,renderer,
 onViewportChange:syncPdfViewport,
 onCancel:()=>palette.select('select'),
 onChange:(reason,replacement)=>{if(replacement){schematic=replacement;editor.schematic=schematic}markDirty();editor.mode==='SIMULATION'?runSimulation():refresh()},
 onSelect:(id,ids=[])=>{const item=ids.length===1?(schematic.getComponent(id)||schematic.getWire(id)):null;properties.render(item,schematic);$('#statusSelection').textContent=ids.length>1?`${ids.length} éléments sélectionnés`:item?`${item.id}${item.type?' · '+item.type:''}`:'Aucune sélection'},
 onStatus:(point,message)=>{if(point)$('#statusPosition').textContent=`x ${Math.round(point.x)} · y ${Math.round(point.y)}`;if(message)$('#statusMessage').textContent=message}
});
const palette=new ComponentPalette($('#palette'),tool=>{editor.tool=tool==='select'?null:tool;$('#canvasEmpty').classList.toggle('hidden',tool!=='select');if(tool!=='wire'){editor.pendingWire=null;editor.preview=null}editor.render()});
const properties=new PropertyPanel($('#properties'),(property,value)=>{const item=schematic.getComponent(editor.selection)||schematic.getWire(editor.selection);if(!item)return;editor.snapshot();if(property==='x'||property==='y')item.position[property]=value;else item[property]=value;markDirty();refresh()},()=>editor.remove());

function projectCaption(){return [schematic.brand,schematic.year].filter(Boolean).length?`${schematic.name} · ${[schematic.brand,schematic.year].filter(Boolean).join(' ')}`:schematic.name}
function markDirty(value=true){dirty=value;document.title=`${value?'• ':''}${schematic.name} — IPCS`;$('#projectTitle').textContent=`${projectCaption()}${value?' — non sauvegardé':''}`}
function refresh(){editor.render(simulation);renderStyles();renderBackground();const item=schematic.getComponent(editor.selection)||schematic.getWire(editor.selection);properties.render(item,schematic)}
function syncPdfViewport(view={pan:editor?.pan||{x:0,y:0},scale:editor?.scale||1}){const layer=$('#pdfViewport');if(layer)layer.style.transform=`translate(${view.pan.x}px,${view.pan.y}px) scale(${view.scale})`}
function renderBackground(){const layer=$('#pdfViewport'),pdf=$('#pdfBackground'),bg=schematic.background,active=bg?.visible&&bg?.dataUrl;if(active){if(pdf.src!==bg.dataUrl)pdf.src=bg.dataUrl;pdf.style.left=`${bg.x??0}px`;pdf.style.top=`${bg.y??0}px`;pdf.style.width=`${bg.width??1200}px`;pdf.style.height=`${bg.height??900}px`;pdf.style.opacity=String((bg.opacity??50)/100);layer.hidden=false;syncPdfViewport()}else{layer.hidden=true;pdf.removeAttribute('src')}$('#canvasWrap').classList.toggle('has-background',!!active)}
function runSimulation(){simulation=solver.solve(schematic);editor.render(simulation);$('#statusMessage').textContent=simulation.converged?`${simulation.poweredCoils.length} bobine(s) alimentée(s) · ${simulation.iterations} passe(s)`:simulation.diagnostic}
function renderStyles(){const root=$('#wireStyles');root.replaceChildren(...schematic.wireStyles.map(style=>{const button=document.createElement('button');button.className=`wire-style ${editor.styleId===style.id?'active':''}`;button.innerHTML=`<span class="wire-swatch" style="background:linear-gradient(135deg,${style.colors.map((color,index)=>`${color} ${index/style.colors.length*100}%,${color} ${(index+1)/style.colors.length*100}%`).join(',')})"></span><span>${style.name}</span>`;button.onclick=()=>{editor.styleId=style.id;renderStyles()};return button}))}
function setMode(mode){editor.setMode(mode);simulation=mode==='SIMULATION'?solver.solve(schematic):null;$('#editMode').classList.toggle('active',mode==='EDIT');$('#simMode').classList.toggle('active',mode==='SIMULATION');$('#statusMode').textContent=mode==='EDIT'?'ÉDITION':'SIMULATION';palette.clear();editor.tool=null;mode==='SIMULATION'?runSimulation():refresh()}
function loadProject(project,handle=null){schematic=project;fileHandle=handle;simulation=null;editor.setSchematic(schematic);setMode('EDIT');markDirty(false);refresh();toast(`Projet « ${schematic.name} » ouvert`)}
function fileToDataUrl(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
function numberValue(selector,fallback){const value=Number($(selector).value);return Number.isFinite(value)?value:fallback}

async function saveProject(){try{fileHandle=await SchematicSerializer.save(schematic,fileHandle);markDirty(false);toast(fileHandle?'Projet sauvegardé dans le fichier local':'Projet téléchargé dans votre dossier Téléchargements')}catch(error){if(error.name!=='AbortError')toast(`Échec de la sauvegarde : ${error.message}`)}}
async function openProject(){try{const result=await SchematicSerializer.open();if(result)loadProject(result.schematic,result.handle);else $('#fileInput').click()}catch(error){if(error.name!=='AbortError')toast(`Impossible d’ouvrir ce projet : ${error.message}`)}}
function fillDialog(project){const bg=project?.background;$('#projectName').value=project?.name||'Nouveau projet';$('#projectBrand').value=project?.brand||'';$('#projectYear').value=project?.year||'';$('#backgroundPdfInput').value='';$('#pdfFileName').textContent=bg?.name||'Aucun fichier sélectionné';$('#showBackground').checked=bg?.visible??true;$('#backgroundOpacity').value=bg?.opacity??50;$('#backgroundOpacityValue').textContent=`${bg?.opacity??50} %`;$('#backgroundX').value=bg?.x??0;$('#backgroundY').value=bg?.y??0;$('#backgroundWidth').value=bg?.width??1200;$('#backgroundHeight').value=bg?.height??900;$('#backgroundSettings').hidden=!bg;$('#snapStepX').value=project?.grid.snapGrid.stepX??10;$('#snapStepY').value=project?.grid.snapGrid.stepY??10;$('#referenceCellWidth').value=project?.grid.referenceGrid.cellWidth??200;$('#referenceCellHeight').value=project?.grid.referenceGrid.cellHeight??150;removeBackground=false}
function openProjectDialog(mode){dialogMode=mode;const editing=mode==='edit';$('#projectDialogTitle').textContent=editing?'Propriétés du projet':'Nouveau projet';$('#projectDialogHelp').textContent=editing?'Modifiez les informations, le calque PDF et les grilles du projet.':'Créez un espace de travail vide. Un plan PDF peut être placé en arrière-plan pour servir de guide.';$('#projectSubmitBtn').textContent=editing?'Appliquer':'Créer le projet';fillDialog(editing?schematic:null);$('#newProjectDialog').showModal();setTimeout(()=>$('#projectName').select())}

$('#newProjectForm').onsubmit=async event=>{event.preventDefault();const name=$('#projectName').value.trim();if(!name)return;const selectedPdf=$('#backgroundPdfInput').files[0];try{let background=dialogMode==='edit'&&!removeBackground?schematic.background:null;if(selectedPdf)background={name:selectedPdf.name,mimeType:selectedPdf.type||'application/pdf',dataUrl:await fileToDataUrl(selectedPdf)};if(background)Object.assign(background,{visible:$('#showBackground').checked,opacity:numberValue('#backgroundOpacity',50),x:numberValue('#backgroundX',0),y:numberValue('#backgroundY',0),width:Math.max(100,numberValue('#backgroundWidth',1200)),height:Math.max(100,numberValue('#backgroundHeight',900))});const data={name,brand:$('#projectBrand').value.trim(),year:$('#projectYear').value?numberValue('#projectYear',null):null,background,grid:{snapGrid:{enabled:true,visible:true,stepX:Math.max(1,numberValue('#snapStepX',10)),stepY:Math.max(1,numberValue('#snapStepY',10))},referenceGrid:{enabled:true,visible:true,cellWidth:Math.max(20,numberValue('#referenceCellWidth',200)),cellHeight:Math.max(20,numberValue('#referenceCellHeight',150))}}};$('#newProjectDialog').close();if(dialogMode==='new'){loadProject(new Schematic(data));fileHandle=null}else{Object.assign(schematic,data);refresh()}markDirty(true);toast(dialogMode==='new'?`Projet « ${name} » créé`:'Propriétés du projet mises à jour')}catch(error){toast(`Lecture du PDF impossible : ${error.message}`)}};
$('#backgroundPdfInput').onchange=event=>{const file=event.target.files[0];$('#pdfFileName').textContent=file?.name||schematic.background?.name||'Aucun fichier sélectionné';if(file){removeBackground=false;$('#backgroundSettings').hidden=false}};
$('#backgroundOpacity').oninput=event=>{$('#backgroundOpacityValue').textContent=`${event.target.value} %`};
$('#removeBackgroundBtn').onclick=()=>{removeBackground=true;$('#backgroundPdfInput').value='';$('#pdfFileName').textContent='Aucun fichier sélectionné';$('#backgroundSettings').hidden=true};
$('#newBtn').onclick=()=>openProjectDialog('new');$('#projectSettingsBtn').onclick=()=>openProjectDialog('edit');$('#closeNewDialog').onclick=()=>$('#newProjectDialog').close();$('#cancelNewProject').onclick=()=>$('#newProjectDialog').close();
$('#saveBtn').onclick=saveProject;$('#openBtn').onclick=openProject;
$('#fileInput').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{loadProject(SchematicSerializer.parse(await file.text()))}catch(error){toast(`Fichier IPCS invalide : ${error.message}`)}finally{event.target.value=''}};
$('#editMode').onclick=()=>setMode('EDIT');$('#simMode').onclick=()=>setMode('SIMULATION');$('#undoBtn').onclick=()=>editor.undo();$('#redoBtn').onclick=()=>editor.redo();$('#zoomIn').onclick=()=>editor.zoom(1.2);$('#zoomOut').onclick=()=>editor.zoom(.8);$('#zoomReset').onclick=()=>editor.zoom(0);
$('#addStyleBtn').onclick=()=>{const colors=prompt('Couleurs CSS séparées par des virgules (1 à 3)','#2d7bd8,#ffffff');if(!colors)return;const list=colors.split(',').map(value=>value.trim()).filter(Boolean).slice(0,3);const id=`STYLE-${Date.now()}`;schematic.wireStyles.push(new WireStyle({id,name:list.join(' / '),colors:list}));editor.styleId=id;markDirty();refresh()};
window.addEventListener('keydown',event=>{if(event.ctrlKey&&event.key.toLowerCase()==='s'){event.preventDefault();saveProject()}if(event.ctrlKey&&event.key.toLowerCase()==='o'){event.preventDefault();openProject()}if(event.ctrlKey&&event.key.toLowerCase()==='n'){event.preventDefault();openProjectDialog('new')}});
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue=''}});
markDirty(false);refresh();
